export type MotorisedPage = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  keywords: string[];
  intro: string;
  highlights: { title: string; text: string }[];
  related: string[];
  faqs: { question: string; answer: string }[];
};

export const motors = [
  { name: "Shuttle Go", load: "Up to 35 kg", bestFor: "Connected domestic curtains", detail: "Built-in Wi-Fi and Bluetooth with Forest Connect app support.", href: "/motorised-curtain-tracks/shuttle-go" },
  { name: "Shuttle iOn", load: "Up to 25 kg", bestFor: "Rechargeable installations", detail: "Battery-powered option for locations without a nearby mains point; up to two bends and up to 8 m on a straight track.", href: "/motorised-curtain-tracks/shuttle-ion" },
  { name: "Shuttle L", load: "Up to 40 kg", bestFor: "Flexible domestic and contract work", detail: "A versatile wired motor with broad control and automation options.", href: "/motorised-curtain-tracks/shuttle-l" },
  { name: "Shuttle AC", load: "Up to 40 kg", bestFor: "Building-management integration", detail: "Designed for hard-wired automation and relay-controlled environments.", href: "/motorised-curtain-tracks/shuttle-ac" },
  { name: "Shuttle M", load: "Up to 70 kg", bestFor: "Heavy curtains and large installations", detail: "The strongest Shuttle option in the range for demanding curtain loads.", href: "/motorised-curtain-tracks/shuttle-m" },
] as const;

export const trackSystems = [
  { name: "FMS", bestFor: "Standard motorised curtains", detail: "Wall or ceiling fixed, one-way or centre opening, with straight and curved configurations.", href: "/motorised-curtain-tracks/fms" },
  { name: "FMS Plus", bestFor: "Architectural installations", detail: "A larger profile for premium interiors and concealed-style detailing.", href: "/motorised-curtain-tracks/fms-plus" },
  { name: "FMS Plus Recess", bestFor: "New builds and clean ceiling lines", detail: "A recessed profile solution for integrating the track into the ceiling design.", href: "/motorised-curtain-tracks/recessed-tracks" },
  { name: "FMS Dual", bestFor: "Hotels and improved blackout", detail: "Two channels operated by one motor with an adjustable overlap for stronger light control.", href: "/motorised-curtain-tracks/hotel-blackout" },
] as const;

const commonFaqs = [
  { question: "Can motorised curtains still be operated by hand?", answer: "Many Forest Shuttle systems include Touch Control and emergency manual operation. The exact feature set depends on the selected motor and control arrangement." },
  { question: "Can TrackFit install curved motorised tracks?", answer: "Yes, subject to survey, bend geometry, curtain load and final manufacturer specification. TrackFit uses a preliminary 10% additional planning allowance per bend when assessing motor load." },
  { question: "Do you supply and install the complete system?", answer: "TrackFit can review the opening, curtain load, track profile, fixing, power location and controls before supplying and installing the agreed system." },
];

export const motorisedPages: MotorisedPage[] = [
  {
    slug: "motors", title: "Forest Shuttle Motor Comparison", eyebrow: "Choose the motor", description: "Compare Forest Shuttle Go, iOn, L, AC and M curtain motors by load, power and control requirements.", keywords: ["Forest Shuttle motor comparison", "electric curtain motor", "motorised curtain motor"], intro: "The right motor depends on more than curtain weight. Power availability, bends, track length, control method and building integration all affect the final choice.",
    highlights: motors.map((motor) => ({ title: `${motor.name}- ${motor.load}`, text: `${motor.bestFor}. ${motor.detail}` })), related: ["controls", "curved-tracks", "heavy-curtains"], faqs: commonFaqs,
  },
  {
    slug: "track-systems", title: "Motorised Curtain Track Systems", eyebrow: "Choose the track", description: "Explore Forest FMS, FMS Plus, recessed and dual motorised curtain-track systems.", keywords: ["motorised curtain track systems", "Forest FMS", "recessed electric curtain track"], intro: "The motor provides movement; the track determines how the curtain is supported, drawn, curved and integrated into the room.", highlights: trackSystems.map((system) => ({ title: system.name, text: `${system.bestFor}. ${system.detail}` })), related: ["fms", "recessed-tracks", "hotel-blackout"], faqs: commonFaqs,
  },
  {
    slug: "controls", title: "Motorised Curtain Controls", eyebrow: "Control the system", description: "Understand touch, remote, app, voice, smart-home and building-management control for motorised curtains.", keywords: ["motorised curtain controls", "smart curtain controls", "electric curtains app"], intro: "Control can be as simple as gently pulling the curtain or as advanced as scheduled scenes, voice control and building-management integration.", highlights: [
      { title: "Touch and remote", text: "Open and close curtains using Touch Control, a handheld remote or a wireless wall switch where compatible." },
      { title: "App and voice", text: "Selected configurations support Forest Connect, Google Home, Amazon Alexa and other smart-home pathways." },
      { title: "Home automation", text: "Shuttle M and L can support advanced integration including Z-Wave options and compatible automation systems." },
      { title: "Hotel and BMS", text: "Relay and hard-wired control can connect motorised curtains to hotel or building-management systems." },
    ], related: ["smart-home", "shuttle-go", "shuttle-ac"], faqs: commonFaqs,
  },
  {
    slug: "curved-tracks", title: "Curved Motorised Curtain Tracks", eyebrow: "Bays and bends", description: "Motorised curtain tracks for bay windows, curved walls and complex layouts, professionally planned and installed.", keywords: ["curved motorised curtain track", "electric curtain track bay window", "motorised bay window curtains"], intro: "Curves increase resistance and must be included in motor planning. TrackFit applies a preliminary 10% additional load allowance per bend and confirms the exact geometry before manufacture.", highlights: [
      { title: "Bend-by-bend planning", text: "The curtain weight, number of bends, bend radius and complete travel path are reviewed together." },
      { title: "FMS curved systems", text: "Forest FMS and FMS Plus can be bent or reverse-bent for suitable project layouts." },
      { title: "Battery option", text: "Shuttle iOn can be considered for suitable curved tracks with up to two bends." },
      { title: "Survey first", text: "Templates, measurements and fixing structure must be confirmed before production." },
    ], related: ["bay-windows", "shuttle-ion", "fms"], faqs: commonFaqs,
  },
  {
    slug: "recessed-tracks", title: "Recessed Motorised Curtain Tracks", eyebrow: "Architectural integration", description: "Concealed and recessed motorised curtain tracks for new builds, renovations and premium interiors.", keywords: ["recessed motorised curtain track", "concealed electric curtain track", "motorised curtain track new build"], intro: "Recessed tracks need early coordination between the designer, builder, electrician, ceiling contractor and curtain-track installer.", highlights: [
      { title: "FMS Plus Recess", text: "A dedicated recessed profile creates a clean ceiling line while supporting the motorised track." },
      { title: "Power planning", text: "Motor position, cable route, isolation and access must be designed before ceilings are closed." },
      { title: "Ceiling support", text: "The recess detail must provide continuous, suitable fixing support for the complete system." },
      { title: "Service access", text: "The motor, controls and track components must remain accessible for commissioning and maintenance." },
    ], related: ["new-builds", "fms-plus", "installation"], faqs: commonFaqs,
  },
  {
    slug: "smart-home", title: "Smart-Home Motorised Curtains", eyebrow: "Connected living", description: "App, voice and home-automation options for smart motorised curtain tracks.", keywords: ["smart curtain tracks", "Alexa motorised curtains", "Google Home curtain tracks"], intro: "Smart control should be selected around the system already used in the property rather than added as an afterthought.", highlights: [
      { title: "Forest Connect", text: "Control compatible systems through the Forest Connect app and create scheduled curtain scenes." },
      { title: "Voice assistants", text: "Selected configurations can work with Google Home, Amazon Alexa and other supported ecosystems." },
      { title: "Shuttle Go", text: "Built-in Wi-Fi and Bluetooth make Shuttle Go a simple connected option for standard domestic curtains." },
      { title: "Advanced integration", text: "Larger automation systems may require a dongle, connector, relay interface or automation engineer." },
    ], related: ["controls", "shuttle-go", "shuttle-l"], faqs: commonFaqs,
  },
  {
    slug: "installation", title: "Motorised Curtain Track Installation", eyebrow: "Survey to commissioning", description: "Professional motorised curtain-track installation across the UK for homes, hotels and commercial projects.", keywords: ["motorised curtain track installation", "electric curtain track installers", "smart curtain installers UK"], intro: "A reliable installation starts with the curtain, opening, fixing structure, electrical provision and control strategy being treated as one system.", highlights: [
      { title: "Survey", text: "We review dimensions, curtain construction, fixing substrate, track route, bends and access." },
      { title: "Specification", text: "The motor, track profile, carriers, brackets, controls and power arrangement are agreed." },
      { title: "Installation", text: "The system is fitted, aligned and tested through the complete curtain travel." },
      { title: "Commissioning", text: "Limits, controls, opening direction and user operation are checked before handover." },
    ], related: ["motors", "track-systems", "controls"], faqs: commonFaqs,
  },
  { slug: "shuttle-go", title: "Forest Shuttle Go Motor", eyebrow: "Connected domestic motor", description: "Forest Shuttle Go motorised curtain-track installation with built-in Wi-Fi and Bluetooth for curtains up to 35 kg without curves.", keywords: ["Forest Shuttle Go", "Shuttle Go curtain motor", "WiFi curtain track"], intro: "Shuttle Go is the natural starting point for standard domestic motorised curtains where simple app connectivity and value matter.", highlights: [{ title: "35 kg capacity", text: "Published for curtains up to 35 kg without curves." }, { title: "Wi-Fi and Bluetooth", text: "Built-in connectivity supports the Forest Connect app without a separate Wi-Fi dongle." }, { title: "Domestic focus", text: "A practical, cost-effective direction for suitable home installations." }, { title: "Five-year warranty", text: "Forest publishes a five-year motor warranty for Shuttle Go." }], related: ["motors", "smart-home", "controls"], faqs: commonFaqs },
  { slug: "shuttle-ion", title: "Forest Shuttle iOn Battery Motor", eyebrow: "Rechargeable curtain control", description: "Rechargeable Forest Shuttle iOn curtain motor for curtains up to 25 kg and suitable tracks up to 8 metres straight.", keywords: ["Forest Shuttle iOn", "battery motorised curtain track", "rechargeable curtain motor"], intro: "Shuttle iOn is designed for locations where running mains power to the curtain track is difficult or undesirable.", highlights: [{ title: "25 kg capacity", text: "Suitable for curtains up to 25 kg on the published straight-track configuration." }, { title: "Rechargeable battery", text: "The removable lithium-ion battery can last up to six months depending on track size, load and use." }, { title: "Up to two bends", text: "Forest publishes suitability for curved tracks with up to two bends." }, { title: "Up to 8 m straight", text: "The published straight-track length is up to eight metres." }], related: ["motors", "curved-tracks", "battery-powered"], faqs: commonFaqs },
  { slug: "shuttle-l", title: "Forest Shuttle L Motor", eyebrow: "Versatile wired motor", description: "Forest Shuttle L motorised curtain track for curtains up to 40 kg with broad control and automation options.", keywords: ["Forest Shuttle L", "40kg curtain motor", "Forest motorised track"], intro: "Shuttle L provides a flexible step up for domestic and contract projects requiring a 40 kg published load limit and wider integration choices.", highlights: [{ title: "40 kg capacity", text: "Published maximum curtain weight without curves is 40 kg." }, { title: "Quiet operation", text: "Published noise level is below 40 dB(A)." }, { title: "Automation options", text: "Compatible configurations include RF, Wi-Fi dongle and optional Z-Wave." }, { title: "Ten-year warranty", text: "Forest publishes a ten-year motor warranty." }], related: ["motors", "controls", "smart-home"], faqs: commonFaqs },
  { slug: "shuttle-ac", title: "Forest Shuttle AC Motor", eyebrow: "Building automation", description: "Forest Shuttle AC motor for building-management and hard-wired automation applications up to 40 kg.", keywords: ["Forest Shuttle AC", "BMS curtain motor", "building automation curtains"], intro: "Shuttle AC is aimed at projects where the curtains need to be controlled through a building-management or hard-wired automation arrangement.", highlights: [{ title: "40 kg capacity", text: "Published curtain capacity is up to 40 kg." }, { title: "BMS direction", text: "Designed for building-management and live AC control applications." }, { title: "Emergency control", text: "Integrated emergency control supports manual operation during a power interruption." }, { title: "Professional coordination", text: "The controls should be coordinated with the electrical or automation contractor." }], related: ["controls", "commercial", "installation"], faqs: commonFaqs },
  { slug: "shuttle-m", title: "Forest Shuttle M Heavy-Duty Motor", eyebrow: "Maximum Shuttle capacity", description: "Forest Shuttle M motorised curtain track for heavy curtains up to 70 kg without curves.", keywords: ["Forest Shuttle M", "70kg curtain motor", "heavy duty motorised curtain track"], intro: "Shuttle M is the strongest motor in the Shuttle range and the principal direction for heavy curtains and demanding installations.", highlights: [{ title: "70 kg capacity", text: "Published maximum curtain weight without curves is 70 kg." }, { title: "1.5 Nm torque", text: "Higher torque supports more demanding curtain loads." }, { title: "65 W motor", text: "The published maximum power is 65 W." }, { title: "Ten-year warranty", text: "Forest publishes a ten-year motor warranty." }], related: ["heavy-curtains", "motors", "commercial"], faqs: commonFaqs },
  { slug: "fms", title: "Forest FMS Motorised Track", eyebrow: "Core track system", description: "Forest FMS motorised curtain track for straight, curved, wall-fixed and ceiling-fixed installations.", keywords: ["Forest FMS", "FMS motorised curtain track", "Forest electric track"], intro: "FMS is the core Forest motorised track system and works with all Shuttle motors for suitable one-way and centre-opening curtains.", highlights: [{ title: "Up to 14 metres", text: "Published configurations can extend up to 14 m, with single-stack arrangements up to 10 m." }, { title: "Straight or curved", text: "The track can be bent for suitable curved layouts." }, { title: "Wall or ceiling", text: "Compatible wall and ceiling bracket options are available." }, { title: "Wave compatible", text: "Designed to support Forest Wave and other suitable heading arrangements." }], related: ["track-systems", "curved-tracks", "installation"], faqs: commonFaqs },
  { slug: "fms-plus", title: "Forest FMS Plus Track", eyebrow: "Architectural profile", description: "Forest FMS Plus motorised track for premium and recessed curtain-track installations.", keywords: ["Forest FMS Plus", "architectural motorised track", "concealed curtain track"], intro: "FMS Plus offers a more substantial architectural profile and forms the basis of the Forest recessed motorised-track solution.", highlights: [{ title: "Premium detailing", text: "A larger profile suited to considered architectural interiors." }, { title: "Recess pathway", text: "Can be combined with the dedicated recess profile." }, { title: "Curved layouts", text: "The track can be bent or reverse-bent for suitable designs." }, { title: "Wave compatible", text: "Supports regular, rotating and Forest Wave carrier arrangements." }], related: ["track-systems", "recessed-tracks", "new-builds"], faqs: commonFaqs },
  { slug: "hotel-blackout", title: "Motorised Hotel Blackout Tracks", eyebrow: "FMS Dual", description: "Motorised dual-channel hotel curtain tracks designed to improve blackout with one motor and adjustable overlap.", keywords: ["hotel motorised curtains", "FMS Dual", "hotel blackout curtain track"], intro: "FMS Dual uses one motor to operate two curtain channels, creating an adjustable overlap intended to reduce central light leakage.", highlights: [{ title: "Two channels, one motor", text: "A single motor operates both channels." }, { title: "Adjustable overlap", text: "The overlap can be configured to improve blackout at the curtain meeting point." }, { title: "Hotel focus", text: "Designed around guestroom blackout and repeatable multi-room installations." }, { title: "Multiple headings", text: "Supports suitable single, double and wave pleat curtain arrangements." }], related: ["hotels", "track-systems", "controls"], faqs: commonFaqs },
  { slug: "heavy-curtains", title: "Motorised Tracks for Heavy Curtains", eyebrow: "High-load planning", description: "Motorised curtain-track specification for velvet, blackout, lined and interlined heavy curtains.", keywords: ["motorised tracks for heavy curtains", "electric track heavy velvet", "70kg curtain track"], intro: "Heavy curtains require the actual finished moving load to be calculated, not guessed from fabric appearance alone.", highlights: [{ title: "Calculate the load", text: "Include face fabric, lining, interlining, fullness, hems, headings and accessories." }, { title: "Allow for bends", text: "TrackFit adds a preliminary 10% motor-load allowance for every bend." }, { title: "Select headroom", text: "Avoid specifying a motor directly at its absolute published limit." }, { title: "Survey the fixing", text: "The ceiling or wall support must carry the complete track and curtain system." }], related: ["shuttle-m", "motors", "installation"], faqs: commonFaqs },
  { slug: "bay-windows", title: "Motorised Curtain Tracks for Bay Windows", eyebrow: "Curved domestic systems", description: "Electric and motorised curtain tracks designed for bay windows and curved domestic openings.", keywords: ["motorised curtain track bay window", "electric bay curtain track", "smart curtains bay window"], intro: "Bay windows combine bends, changing wall angles, stack space and fixing constraints, so the track must be templated and specified as a complete route.", highlights: [{ title: "Accurate template", text: "Each wall section, angle and curve must be measured before manufacture." }, { title: "Motor allowance", text: "Every bend adds resistance and is included in the planning load." }, { title: "Stack position", text: "The curtain stack and motor location must be planned around the room." }, { title: "Power or battery", text: "Both wired and suitable rechargeable directions can be assessed." }], related: ["curved-tracks", "shuttle-ion", "installation"], faqs: commonFaqs },
  { slug: "new-builds", title: "Motorised Curtain Tracks for New Builds", eyebrow: "Plan before plastering", description: "Early-stage motorised curtain-track planning for new homes, developments and ceiling recesses.", keywords: ["motorised curtain tracks new build", "electric curtains new home", "recessed curtain track planning"], intro: "New-build projects provide the best opportunity to hide tracks, motors and cabling—but only when the details are agreed before ceilings and finishes are completed.", highlights: [{ title: "Early specification", text: "Confirm track route, curtain stack, motor position and recess dimensions before first fix." }, { title: "Electrical coordination", text: "Agree power, isolation and control cabling with the electrician." }, { title: "Continuous support", text: "Provide suitable structure along the full fixing route." }, { title: "Final access", text: "Keep the motor and service components accessible after completion." }], related: ["recessed-tracks", "fms-plus", "installation"], faqs: commonFaqs },
  { slug: "commercial", title: "Commercial Motorised Curtain Tracks", eyebrow: "Contract installations", description: "Commercial motorised curtain-track systems for offices, hospitality, meeting rooms and multi-site projects.", keywords: ["commercial motorised curtain tracks", "electric curtains office", "contract motorised track"], intro: "Commercial systems must balance curtain load, operating frequency, control integration, programme, access and maintainability.", highlights: [{ title: "Project specification", text: "Track schedules, room types and control requirements are reviewed before production." }, { title: "BMS integration", text: "Suitable systems can connect to relay or building-management controls." }, { title: "Phased installation", text: "Work can be coordinated around room access and wider refurbishment programmes." }, { title: "Handover", text: "Operation, limits and controls are tested before completion." }], related: ["shuttle-ac", "controls", "installation"], faqs: commonFaqs },
  { slug: "hotels", title: "Motorised Curtain Tracks for Hotels", eyebrow: "Guestroom automation", description: "Motorised curtains for hotel bedrooms, suites, conference spaces and hospitality projects.", keywords: ["hotel motorised curtain tracks", "automated hotel curtains", "hotel blackout tracks"], intro: "Hotel curtain systems need quiet operation, strong blackout planning, repeatable room specifications and controls that fit the hotel’s operating model.", highlights: [{ title: "Guestroom blackout", text: "FMS Dual can operate two channels with an adjustable overlap." }, { title: "Quiet movement", text: "Shuttle motors are designed for smooth, quiet curtain operation." }, { title: "Hotel controls", text: "Systems can be coordinated with suitable room or building controls." }, { title: "Repeatable delivery", text: "Room schedules and standard details improve consistency across larger projects." }], related: ["hotel-blackout", "controls", "commercial"], faqs: commonFaqs },
  { slug: "battery-powered", title: "Battery-Powered Motorised Curtains", eyebrow: "No nearby power point", description: "Rechargeable motorised curtain tracks using Forest Shuttle iOn for suitable domestic and commercial applications.", keywords: ["battery powered curtain track", "rechargeable electric curtains", "wireless motorised curtains"], intro: "A rechargeable motor can avoid new mains cabling where the curtain weight, track length and bend count remain within the product limits.", highlights: [{ title: "Removable battery", text: "The battery pack can be removed and recharged." }, { title: "Up to six months", text: "Published charge duration is up to six months depending on load, length and use." }, { title: "25 kg limit", text: "The published curtain-weight capacity is up to 25 kg." }, { title: "Two-bend maximum", text: "Forest publishes curved-track suitability up to two bends." }], related: ["shuttle-ion", "curved-tracks", "motors"], faqs: commonFaqs },
];

export const motorisedArticles = [
  ["how-to-choose-a-motorised-curtain-track", "How to Choose the Right Motorised Curtain Track", "A practical guide to motors, tracks, curtain weight, power and controls."],
  ["how-much-do-curtains-weigh", "How Much Do Curtains Weigh?", "How dimensions, fullness, GSM, lining and interlining affect finished curtain weight."],
  ["motorised-tracks-for-bay-windows", "Motorised Curtain Tracks for Bay Windows", "What bends, templates, power and motor capacity mean for bay-window projects."],
  ["battery-vs-mains-powered-curtains", "Battery vs Mains-Powered Motorised Curtains", "Compare rechargeable and wired systems before choosing a motor."],
  ["motorised-tracks-for-heavy-curtains", "Motorised Tracks for Heavy Curtains", "Planning motor capacity for velvet, blackout and interlined curtains."],
  ["alexa-google-home-and-homekit-curtains", "Smart Curtains: Alexa, Google Home and Apple HomeKit", "Understand the different app, voice and connector pathways."],
  ["recessed-tracks-for-new-builds", "Recessed Motorised Tracks for New Builds", "What architects, builders and electricians need to coordinate early."],
  ["hotel-motorised-curtain-systems", "Motorised Curtain Systems for Hotels", "Blackout, controls and repeatable room specifications for hospitality projects."],
  ["centre-opening-vs-one-way-curtains", "Centre-Opening vs One-Way Motorised Curtains", "Compare stack positions, motor placement and practical room use."],
  ["motorised-curtains-during-a-power-cut", "What Happens to Motorised Curtains During a Power Cut?", "Emergency manual operation and system planning explained."],
] as const;

export function getMotorisedPage(slug: string) {
  return motorisedPages.find((page) => page.slug === slug);
}
