import type { AreaSampleReview } from "./types";

const reviewRows: Array<[
  slug: string,
  name: string,
  area: string,
  quote: string,
]> = [
  ["london", "Amelia R.", "Islington", "The fitter arrived on time, explained the options clearly and completed the work neatly. Everything was left clean and the curtains run smoothly."],
  ["central-london", "Theo M.", "Marylebone", "The whole process was straightforward and well organised. The fitter worked carefully, kept us informed and left a very tidy finish."],
  ["north-london", "Priya K.", "Finchley", "We received clear advice before the fitting and the work was completed with care. The track looks neat and feels secure."],
  ["south-london", "Daniel A.", "Dulwich", "The fitter was punctual, polite and careful around the room. The installation was finished neatly and everything was cleared away afterwards."],
  ["east-london", "Leila S.", "Stratford", "Communication was clear from the start and the appointment went smoothly. The finished track looks professional and works exactly as it should."],
  ["west-london", "Marcus T.", "Ealing", "We were given sensible advice about the best position for the track. The fitting was tidy, secure and completed without any fuss."],
  ["reading", "Sophie B.", "Caversham", "The fitter took time to explain the choices and made sure we were happy before starting. The finished installation is neat and level."],
  ["oxford", "Jacob N.", "Headington", "The work was carried out carefully around the existing décor. The room was left clean and the new track looks very smart."],
  ["cambridge", "Hannah P.", "Trumpington", "Booking was easy and the fitter arrived when expected. The advice was helpful and the completed work has a clean, professional finish."],
  ["brighton-and-hove", "Maya D.", "Seven Dials", "The fitter was friendly and professional throughout. The track was installed neatly and the curtains now open and close smoothly."],
  ["canterbury", "Oliver F.", "St Dunstan's", "We appreciated the clear explanation before the work began. The fitting was completed carefully and the area was left spotless."],
  ["chichester", "Rose C.", "Bosham", "The service was calm and straightforward from start to finish. The track looks neat, feels secure and suits the room well."],
  ["crawley", "Ethan G.", "Pound Hill", "We needed several tracks fitted and the process was very well managed. The work was consistent, tidy and completed with care."],
  ["eastbourne", "Alice W.", "Meads", "The fitter arrived promptly and treated the room with care. We were pleased with the tidy installation and overall finish."],
  ["guildford", "Noah L.", "Merrow", "The advice was clear and practical, with no pressure. The track was fitted securely and the finished result looks professional."],
  ["maidstone", "Grace H.", "Bearsted", "Everything was explained in plain language before fitting. The work was neat, the room was left clean and the track operates smoothly."],
  ["royal-tunbridge-wells", "Felix J.", "Southborough", "The fitter worked carefully and checked that we were happy with the position. The completed track is tidy and level."],
  ["slough", "Zara I.", "Langley", "The appointment was easy to arrange and the fitter was courteous throughout. The installation was completed neatly with very little disruption."],
  ["southampton", "Samuel E.", "Ocean Village", "We were kept informed and the fitter arrived as arranged. The work was clean and professional, and the curtains move much better now."],
  ["portsmouth", "Chloe V.", "Southsea", "The fitter gave helpful advice and took care around our furniture and décor. The finished track looks neat and secure."],
  ["winchester", "Arthur Q.", "Fulflood", "A professional and friendly service from beginning to end. The fitting was carried out carefully and everything was left tidy."],
  ["woking", "Isla Y.", "Horsell", "The fitter explained where the track would sit and checked the details with us first. The result is clean and well finished."],
  ["worthing", "Leo U.", "Tarring", "We were pleased with how smoothly the appointment went. The work was completed neatly and the curtains now run without catching."],
  ["st-albans", "Freya O.", "Marshalswick", "The advice was easy to understand and the fitter worked with real care. The track is secure and the room was left clean."],
  ["watford", "Adam Z.", "Cassiobury", "The fitter was punctual and professional, and made sure the position was right before starting. The finish is very tidy."],
  ["hemel-hempstead", "Nina X.", "Boxmoor", "We found the process simple and well organised. The installation was completed carefully and the finished track looks neat in the room."],
  ["high-wycombe", "Henry R.", "Hazlemere", "The fitter took time to get everything level and properly aligned. The work was neat and there was no mess left behind."],
  ["aylesbury", "Layla M.", "Fairford Leys", "Clear advice, polite service and a tidy installation. We were shown how everything worked before the fitter left."],
  ["milton-keynes", "Oscar K.", "Wolverton", "Several tracks were fitted for us and each one was finished to the same good standard. The whole visit was straightforward."],
  ["bedford", "Eva A.", "Biddenham", "The fitter listened to what we wanted and explained the best option. The work was carried out neatly and carefully."],
  ["luton", "Mohammed S.", "Stopsley", "The appointment ran on time and the fitter was respectful of our home. The track looks professional and works smoothly."],
  ["chelmsford", "Imogen T.", "Great Baddow", "We received useful advice without any jargon. The fitting was quick, tidy and completed with close attention to the finish."],
  ["colchester", "George B.", "Lexden", "The fitter checked the position with us and worked carefully throughout. We are happy with the neat and secure result."],
  ["basildon", "Aisha N.", "Langdon Hills", "The service was friendly and efficient. Everything was explained clearly and the room was left just as tidy as it was before."],
  ["southend-on-sea", "Thomas P.", "Leigh-on-Sea", "The fitter arrived as planned and completed the installation with care. The curtains now hang properly and move easily."],
  ["bristol", "Lucy F.", "Redland", "We were impressed by how tidy and considerate the fitter was. The track was positioned well and the finish looks professional."],
  ["bath", "Edward D.", "Widcombe", "The work was handled carefully around the existing decoration. The fitter explained each step and left a clean, discreet finish."],
  ["bournemouth", "Millie C.", "Westbourne", "The booking and fitting were both straightforward. The track feels secure, looks neat and the curtains glide smoothly."],
  ["poole", "Jack G.", "Parkstone", "We had clear advice about the available options and never felt rushed. The installation was tidy and well finished."],
  ["exeter", "Poppy W.", "Heavitree", "The fitter was polite, punctual and careful in the room. Everything was tested before leaving and the area was left clean."],
  ["plymouth", "William H.", "Plymstock", "The new track was fitted securely and neatly. We appreciated the clear communication and the care taken with our home."],
  ["salisbury", "Ruby L.", "Harnham", "The fitter explained the plan before starting and worked in a very organised way. The finished result is simple and tidy."],
  ["swindon", "James E.", "Old Town", "A smooth service from the first conversation to the completed fitting. The track looks good and works without any issues."],
  ["gloucester", "Matilda J.", "Quedgeley", "The advice was practical and easy to follow. The installation was completed neatly and the fitter cleaned up thoroughly afterwards."],
  ["cheltenham", "Benjamin V.", "Pittville", "Great care was taken around the room and the fitter checked the alignment before finishing. We are pleased with the result."],
  ["taunton", "Florence Q.", "Trull", "The fitter was friendly, careful and well prepared. The track was installed neatly and the curtains now move smoothly."],
  ["torquay", "Sebastian Y.", "Babbacombe", "Everything was handled professionally and with minimal disruption. The finished track looks tidy and feels properly secure."],
  ["blackburn", "Emily U.", "Darwen", "The fitter arrived on time, talked us through the best option and completed the work neatly. The room was left clean afterwards."],
  ["manchester", "Yusuf O.", "Ancoats", "We needed tracks fitted in more than one room and the whole process was well organised. Each installation looks neat and consistent."],
  ["birmingham", "Abigail X.", "Harborne", "The service was professional and uncomplicated. The fitter worked carefully, checked everything and left a very tidy finish."],
  ["leeds", "Alexander Z.", "Chapel Allerton", "The fitter gave clear advice and made sure the track position suited the room. The work was clean and completed with care."],
  ["liverpool", "Charlotte I.", "Aigburth", "We were kept informed throughout the visit and the fitter was respectful of the property. The track now works smoothly and looks smart."],
  ["sheffield", "Isaac R.", "Nether Edge", "The fitting was carried out carefully and everything was checked before completion. We were happy with the neat, level finish."],
  ["nottingham", "Sienna M.", "Mapperley", "The fitter was approachable and explained the options clearly. The installation was tidy and the room was left in good order."],
  ["leicester", "Reuben K.", "Stoneygate", "A straightforward appointment with helpful advice and no mess. The track is secure and the finished work looks professional."],
  ["newcastle", "Harriet A.", "Jesmond", "The fitter took care around the existing furnishings and completed the work neatly. The curtains now open and close with ease."],
  ["york", "Max S.", "Fulford", "The whole service felt organised and professional. The fitter arrived as arranged, worked tidily and left us with a clean finish."],
];

export const sampleAreaReviews = Object.fromEntries(
  reviewRows.map(([slug, name, area, quote]) => [
    slug,
    { name, area, quote, sample: true } satisfies AreaSampleReview,
  ]),
) as Record<string, AreaSampleReview>;

export function getSampleAreaReview(slug: string) {
  return sampleAreaReviews[slug];
}
