import type { AreaSampleReview } from "./types";

const reviewRows: Array<[
  slug: string,
  name: string,
  area: string,
  quote: string,
]> = [
  ["london", "Amelia R.", "Islington", "The sample journey shows how access details and the curtain specification could be gathered before a London installation."],
  ["central-london", "Theo M.", "Marylebone", "This placeholder highlights the value of checking loading access and ceiling height before bringing long track sections into a central building."],
  ["north-london", "Priya K.", "Finchley", "The example reflects the careful measuring a multi-angle bay needs before the track and curtain return can be planned."],
  ["south-london", "Daniel A.", "Dulwich", "This sample focuses on getting enough projection around a radiator while keeping the bay track visually discreet."],
  ["east-london", "Leila S.", "Stratford", "The placeholder demonstrates why confirming a concrete ceiling and concierge procedure early makes an apartment installation easier to plan."],
  ["west-london", "Marcus T.", "Ealing", "This example review describes a double-track layout planned around cornicing and the available depth above a period window."],
  ["reading", "Sophie B.", "Caversham", "The sample shows how stack-back and handle clearance can be considered together across a wide set of garden doors."],
  ["oxford", "Jacob N.", "Headington", "This placeholder centres on protecting older finishes and finding sound structure rather than fixing into fragile plaster."],
  ["cambridge", "Hannah P.", "Trumpington", "The example describes coordinating a ceiling track with full-height glazing in a modern family space."],
  ["brighton-and-hove", "Maya D.", "Seven Dials", "This sample reflects the extra measuring and safe access needed for a tall bay in a converted period property."],
  ["canterbury", "Oliver F.", "St Dunstan's", "The placeholder notes how an uneven period wall can be measured at track height before choosing the mounting route."],
  ["chichester", "Rose C.", "Bosham", "This example considers curtain stack-back beside wide coastal glazing without claiming a completed local project."],
  ["crawley", "Ethan G.", "Pound Hill", "The sample demonstrates the benefit of checking each room even where several windows appear to share the same layout."],
  ["eastbourne", "Alice W.", "Meads", "This placeholder focuses on planning safe access and reliable support at a tall seafront bay."],
  ["guildford", "Noah L.", "Merrow", "The example describes a heavy curtain track planned across wide doors with joins and support positions considered together."],
  ["maidstone", "Grace H.", "Bearsted", "This sample shows why the construction behind newly plastered bay reveals should be confirmed before drilling."],
  ["royal-tunbridge-wells", "Felix J.", "Southborough", "The placeholder reflects accurate measuring at track height where an older bay changes angle between sill and ceiling."],
  ["slough", "Zara I.", "Langley", "This example highlights a repeatable apartment-room plan that still checks service zones and ceiling changes in every space."],
  ["southampton", "Samuel E.", "Ocean Village", "The sample considers concierge access, balcony-door clearance and the actual ceiling build-up in one planning process."],
  ["portsmouth", "Chloe V.", "Southsea", "This placeholder describes finding enough curtain projection in a compact bay without crowding the room."],
  ["winchester", "Arthur Q.", "Fulflood", "The example focuses on locating sound structure beyond delicate finishes in a tall period room."],
  ["woking", "Isla Y.", "Horsell", "This sample demonstrates how side space and door controls affect the useful length of a bifold-door track."],
  ["worthing", "Leo U.", "Tarring", "The placeholder balances light-blocking overlap with the space needed to stack curtains beside a broad window."],
  ["st-albans", "Freya O.", "Marshalswick", "This example considers blinds, radiator projection and bay angles before selecting the track position."],
  ["watford", "Adam Z.", "Cassiobury", "The sample compares wall and ceiling mounting against a solid lintel and the required curtain projection."],
  ["hemel-hempstead", "Nina X.", "Boxmoor", "This placeholder shows why later extensions can make the fixing construction differ between otherwise similar rooms."],
  ["high-wycombe", "Henry R.", "Hazlemere", "The example uses a level track datum while checking curtain drop across an uneven ceiling line."],
  ["aylesbury", "Layla M.", "Fairford Leys", "This sample reflects using new-build construction information to avoid concealed steel and service zones."],
  ["milton-keynes", "Oscar K.", "Wolverton", "The placeholder describes coordinating a curtain track with blinds and ventilation above modern glazing."],
  ["bedford", "Eva A.", "Biddenham", "This example measures the radiator and deepest part of a bay before deciding the required track projection."],
  ["luton", "Mohammed S.", "Stopsley", "The sample considers whether curtains should stack inside or outside a shallow bay before the route is ordered."],
  ["chelmsford", "Imogen T.", "Great Baddow", "This placeholder highlights a rooflight and steel beam that need checking around a wide extension opening."],
  ["colchester", "George B.", "Lexden", "The example measures a tapered period reveal at track height instead of assuming the sides are parallel."],
  ["basildon", "Aisha N.", "Langdon Hills", "This sample maps the construction change where an original house meets a newer extension."],
  ["southend-on-sea", "Thomas P.", "Leigh-on-Sea", "The placeholder considers privacy overlap and open-view stack-back across a broad coastal window."],
  ["bristol", "Lucy F.", "Redland", "This example differentiates exposed structure from a suspended ceiling when planning tracks across a converted property."],
  ["bath", "Edward D.", "Widcombe", "The sample focuses on an acceptable fixing zone below decorative plaster in a tall Georgian room."],
  ["bournemouth", "Millie C.", "Westbourne", "This placeholder considers balcony-door handles, wide glazing and managed access in a coastal apartment."],
  ["poole", "Jack G.", "Parkstone", "The example checks recess depth and curtain-heading clearance before choosing a double-track arrangement."],
  ["exeter", "Poppy W.", "Heavitree", "This sample identifies a lowered ceiling before a long track is fixed in a converted town property."],
  ["plymouth", "William H.", "Plymstock", "The placeholder describes robust support for regularly operated curtains across a wide waterfront window."],
  ["salisbury", "Ruby L.", "Harnham", "This example checks a narrow stair route before deciding where a joined track can be safely supported."],
  ["swindon", "James E.", "Old Town", "The sample uses construction information to plan around a steel lintel above a renovated window."],
  ["gloucester", "Matilda J.", "Quedgeley", "This placeholder considers brick, steel and lined sections along one dockside-conversion track route."],
  ["cheltenham", "Benjamin V.", "Pittville", "The example aligns a track to the functional window rather than following a slightly uneven decorative cornice."],
  ["taunton", "Florence Q.", "Trull", "This sample checks gates, stairs and ceiling beams before selecting track sections for a rural property."],
  ["torquay", "Sebastian Y.", "Babbacombe", "The placeholder measures a hillside bay at the intended track height and checks curtain drop at several points."],
  ["blackburn", "Emily U.", "Darwen", "This example accounts for changing plaster depth before selecting fixings into a stone wall."],
  ["manchester", "Yusuf O.", "Ancoats", "The sample separates exposed concrete from an acoustic ceiling zone when planning a mill-conversion installation."],
  ["birmingham", "Abigail X.", "Harborne", "This placeholder maps the former external wall before supporting a long track across an extension."],
  ["leeds", "Alexander Z.", "Chapel Allerton", "The example checks the tightest return in a deep stone bay rather than relying on the centre section alone."],
  ["liverpool", "Charlotte I.", "Aigburth", "This sample confirms whether an apartment ceiling edge is structural or a services bulkhead before fixing."],
  ["sheffield", "Isaac R.", "Nether Edge", "The placeholder uses a level datum and checks both curtain drops in a room with a sloping ceiling line."],
  ["nottingham", "Sienna M.", "Mapperley", "This example plots brick, steel and lined surfaces before positioning joins in a converted building."],
  ["leicester", "Reuben K.", "Stoneygate", "The sample checks support separately around each section of a bay with mixed hidden construction."],
  ["newcastle", "Harriet A.", "Jesmond", "This placeholder verifies joist direction in both rooms of a Tyneside flat rather than assuming they match."],
  ["york", "Max S.", "Fulford", "The example checks a compact stair route before specifying a supported join for a long period-room track."],
];

export const sampleAreaReviews = Object.fromEntries(
  reviewRows.map(([slug, name, area, quote]) => [
    slug,
    { name, area, quote, sample: true } satisfies AreaSampleReview,
  ]),
) as Record<string, AreaSampleReview>;

export function getSampleAreaReview(slug: string) {
  return sampleAreaReviews[slug];
}
