import type { Area } from "../types";

export const homeCountiesAreas = [
  {
    slug: "st-albans", name: "St Albans", region: "Hertfordshire", regionGroup: "Home Counties",
    intro: "TrackFit provides nationwide curtain-track installation in St Albans for period terraces, bay-fronted family houses, village homes and modern apartments. Decorative finishes and altered older buildings call for careful checks behind the visible plaster.",
    metaDescription: "St Albans curtain-track installation for period homes, bays, apartments and commercial properties from TrackFit.",
    propertyFocus: ["Victorian and Edwardian terraces", "Bay-fronted semis and detached family homes", "Village properties, apartments and modern extensions"],
    challenges: ["Older plaster, cornices and altered lintels", "Deep bays and limited returns around radiators", "Central parking and managed-building access"],
    commercial: ["Hotels, offices and serviced accommodation", "Schools, healthcare and care homes", "Retail spaces and residential developments"],
    areas: ["Marshalswick", "Fleetville", "Sopwell", "London Colney", "Harpenden", "Wheathampstead"],
    localNote: "In a St Albans bay, check whether shutters, blinds or a radiator occupy the same projection zone. Layering window treatments without measuring their operating paths can leave curtains dragging or unable to close.",
    faqs: [
      { question: "Can a track work around existing blinds in a St Albans bay?", answer: "Yes where there is enough projection and sound structure. The blind, handles, radiator and curtain heading all need to be measured together." },
      { question: "Can tracks be fitted in an older terrace?", answer: "Often, yes. The installation should locate sound masonry or timber and avoid relying on fragile plaster or decorative cornicing." },
      { question: "Do you cover Harpenden and London Colney?", answer: "Yes. Both are included in the nearby St Albans coverage shown here." },
    ], relatedAreaSlugs: ["watford", "hemel-hempstead", "luton", "north-london"], guideSlugs: ["how-to-fit-curtain-track-over-blinds", "curtain-tracks-for-bay-windows"],
  },
  {
    slug: "watford", name: "Watford", region: "Hertfordshire", regionGroup: "Home Counties",
    intro: "TrackFit installs curtain tracks across Watford through its nationwide service, covering inter-war homes, period terraces, apartments and commercial interiors. Bay windows and newer concrete-framed buildings need different fixing information even when the finished room looks similar.",
    metaDescription: "Watford curtain-track fitting for period and inter-war homes, apartments and commercial properties by TrackFit.",
    propertyFocus: ["Inter-war semis and bay-fronted family homes", "Victorian terraces and converted houses", "Town-centre apartments and new developments"],
    challenges: ["Concrete ceilings or dry lining in apartment blocks", "Bay returns obstructed by radiators or furniture", "Parking controls and managed access near the centre"],
    commercial: ["Offices, healthcare and education", "Hotels and serviced accommodation", "Retail interiors, care homes and developments"],
    areas: ["Nascot Wood", "Cassiobury", "Oxhey", "Garston", "Bushey", "Rickmansworth"],
    localNote: "A Watford semi may have a solid lintel above the window but a lighter ceiling fixing zone. Comparing wall and ceiling options against the curtain load can avoid drilling into an unsuitable part of the opening.",
    faqs: [
      { question: "Is wall or ceiling mounting better for a Watford bay?", answer: "It depends on the bay shape, available fixing material, cornice, radiator projection and curtain heading. Neither method is automatically preferable." },
      { question: "Can TrackFit install in town-centre apartments?", answer: "Yes, subject to construction and building-access checks such as parking, lift use, contractor booking and permitted fixing depth." },
      { question: "Do you cover Bushey and Rickmansworth?", answer: "Yes. Both are represented within this Watford coverage page." },
    ], relatedAreaSlugs: ["st-albans", "hemel-hempstead", "north-london", "high-wycombe"], guideSlugs: ["ceiling-vs-wall-mounted-curtain-tracks", "fitting-curtain-tracks-under-steel-lintels"],
  },
  {
    slug: "hemel-hempstead", name: "Hemel Hempstead", region: "Hertfordshire", regionGroup: "Home Counties",
    intro: "TrackFit's nationwide service covers curtain-track fitting in Hemel Hempstead for New Town housing, older village properties, apartments and extended family homes. Construction can vary significantly between original buildings and later alterations.",
    metaDescription: "Hemel Hempstead curtain-track installation for New Town homes, village properties, apartments and extensions by TrackFit.",
    propertyFocus: ["New Town terraces, semis and maisonettes", "Older properties around the Old Town and nearby villages", "Modern apartments and extended detached homes"],
    challenges: ["Concrete, blockwork and plasterboard across different building eras", "Wide rear extensions and patio-door spans", "Previous repairs or lightweight finishes around openings"],
    commercial: ["Offices and business premises", "Healthcare, education and care settings", "Hotels, retail and residential developments"],
    areas: ["Boxmoor", "Apsley", "Leverstock Green", "Gadebridge", "Bennetts End", "Kings Langley"],
    localNote: "In Hemel Hempstead housing, identical window dimensions do not confirm identical construction. Extensions, overboarding and previous refurbishments can change the available fixing depth from room to room.",
    faqs: [
      { question: "Can tracks be fitted to plasterboard in a Hemel Hempstead home?", answer: "Sometimes, but curtain weight and what lies behind the board determine the fixing method. Plasterboard condition alone is not enough information." },
      { question: "Can you span new patio doors?", answer: "Yes. Track stiffness, support spacing, curtain weight, door movement and stack-back all need to suit the opening." },
      { question: "Do you cover Boxmoor and Apsley?", answer: "Yes. Both areas are included within Hemel Hempstead coverage." },
    ], relatedAreaSlugs: ["st-albans", "watford", "luton", "aylesbury"], guideSlugs: ["fitting-curtain-tracks-to-plasterboard", "curtain-tracks-for-sliding-doors"],
  },
  {
    slug: "high-wycombe", name: "High Wycombe", region: "Buckinghamshire", regionGroup: "Home Counties",
    intro: "TrackFit provides nationwide curtain-track installation around High Wycombe for Victorian terraces, hillside homes, suburban properties and modern apartments. Sloping sites and altered interiors make level setting and structural checks particularly important.",
    metaDescription: "High Wycombe curtain-track fitting for terraces, hillside homes, apartments and commercial properties from TrackFit.",
    propertyFocus: ["Victorian terraces and older town properties", "Hillside semis and detached suburban homes", "Modern apartments, estates and large extensions"],
    challenges: ["Uneven walls or ceilings in altered properties", "Deep bays and masonry fixing surfaces", "Long glazed openings in expanded family spaces"],
    commercial: ["Offices, retail and hospitality", "Healthcare, education and care homes", "Residential developments and managed properties"],
    areas: ["Downley", "Hazlemere", "Wycombe Marsh", "Loudwater", "Flackwell Heath", "Marlow"],
    localNote: "For a High Wycombe hillside property, use a level datum at the intended track height rather than following a visibly sloping ceiling edge. Curtain drops and clearances should be checked across the whole opening.",
    faqs: [
      { question: "Can a track be installed where the ceiling is not level?", answer: "Often, yes. The route should be set out deliberately, with any variation in curtain drop and the availability of sound fixing points considered first." },
      { question: "Can you fit heavy curtains over a wide opening?", answer: "Yes where the track profile, brackets, joins and substrate are specified for the total load and intended frequency of use." },
      { question: "Do you cover Hazlemere and Marlow?", answer: "Yes. Both are included within nearby High Wycombe coverage." },
    ], relatedAreaSlugs: ["aylesbury", "slough", "reading", "watford"], guideSlugs: ["curtain-track-installation-on-uneven-walls", "best-curtain-tracks-for-heavy-curtains"],
  },
  {
    slug: "aylesbury", name: "Aylesbury", region: "Buckinghamshire", regionGroup: "Home Counties",
    intro: "TrackFit installs curtain tracks in Aylesbury through its nationwide service, covering established estates, period town properties, village homes and new developments. The practical fitting approach varies between solid masonry, dry-lined construction and timber-framed extensions.",
    metaDescription: "Aylesbury curtain-track installation for estates, period and village homes, new builds and commercial properties by TrackFit.",
    propertyFocus: ["Established estate housing and suburban family homes", "Period town properties and nearby village houses", "New-build developments and modern extensions"],
    challenges: ["Dry lining and lightweight finishes in newer homes", "Concrete or steel above wide openings", "Long routes and access planning for village properties"],
    commercial: ["Healthcare, education and care homes", "Offices, retail and hospitality", "Residential developments and property portfolios"],
    areas: ["Fairford Leys", "Bedgrove", "Broughton", "Watermead", "Stone", "Wendover"],
    localNote: "In a new Aylesbury development, ask for the wall and ceiling build-up before assuming standard plasterboard fixings are appropriate. Developer information can reveal steel, service zones or structural backing not visible in the room.",
    faqs: [
      { question: "Can tracks be installed in an Aylesbury new build?", answer: "Yes, after checking the permitted fixing locations, backing, services and curtain load. Developer drawings or handover information can be useful." },
      { question: "Do rural properties require different planning?", answer: "The track selection may be the same, but travel access, room height, old finishes and the route for long materials should be described in advance." },
      { question: "Do you cover Fairford Leys and Wendover?", answer: "Yes. Both are included in the Aylesbury coverage represented here." },
    ], relatedAreaSlugs: ["high-wycombe", "milton-keynes", "oxford", "hemel-hempstead"], guideSlugs: ["fitting-curtain-tracks-to-plasterboard", "what-information-needed-for-curtain-track-quote"],
  },
  {
    slug: "milton-keynes", name: "Milton Keynes", region: "Buckinghamshire", regionGroup: "Home Counties",
    intro: "TrackFit provides nationwide curtain-track fitting across Milton Keynes for modern estates, new apartments, village properties and commercial developments. Full-height glazing, dry-lined walls and repeatable room layouts make accurate construction information valuable.",
    metaDescription: "Milton Keynes curtain-track installation for modern homes, apartments, village properties and commercial developments by TrackFit.",
    propertyFocus: ["Modern estate housing and detached family homes", "New apartments and mixed-use developments", "Older village properties within the wider urban area"],
    challenges: ["Plasterboard linings, engineered structure and concealed services", "Wide windows, patio doors and limited wall above glazing", "Multi-room schedules requiring consistent but verified fixing plans"],
    commercial: ["Offices, hospitality and serviced accommodation", "Healthcare, education and care homes", "Retail spaces and residential developments"],
    areas: ["Bletchley", "Wolverton", "Stony Stratford", "Newport Pagnell", "Woburn Sands", "Shenley Brook End"],
    localNote: "In a Milton Keynes new-build project, coordinate curtain tracks with blinds, ventilation and window-opening controls before fixing. Several systems can compete for the same shallow ceiling or head zone.",
    faqs: [
      { question: "Can tracks be coordinated with blinds in a new apartment?", answer: "Yes. Their projection, operating clearances and separate fixing zones should be considered together before either system is installed." },
      { question: "Can TrackFit handle a multi-room development schedule?", answer: "The scope can be assessed from drawings, room quantities, track specification, access requirements and programme information without implying guaranteed capacity." },
      { question: "Do you cover Bletchley and Newport Pagnell?", answer: "Yes. Both are part of Milton Keynes coverage." },
    ], relatedAreaSlugs: ["bedford", "aylesbury", "luton", "oxford"], guideSlugs: ["how-to-fit-curtain-track-over-blinds", "curtain-tracks-for-floor-to-ceiling-windows"],
  },
  {
    slug: "bedford", name: "Bedford", region: "Bedfordshire", regionGroup: "Home Counties",
    intro: "TrackFit's nationwide curtain-track service covers Bedford's Victorian terraces, riverside apartments, suburban homes and commercial interiors. Older bays, high rooms and modern glazing each need a distinct balance of support, projection and access.",
    metaDescription: "Bedford curtain-track fitting for Victorian homes, riverside apartments, suburban properties and commercial interiors from TrackFit.",
    propertyFocus: ["Victorian and Edwardian terraces", "Riverside and town-centre apartments", "Suburban semis, detached homes and extensions"],
    challenges: ["Bay windows, tall rooms and older plaster", "Concrete or dry-lined apartment construction", "Wide doors and radiators affecting track projection"],
    commercial: ["Education, healthcare and care homes", "Offices, hospitality and serviced accommodation", "Retail and residential developments"],
    areas: ["Kempston", "Brickhill", "Putnoe", "Goldington", "Biddenham", "Clapham"],
    localNote: "A Bedford bay with a deep sill may require less projection than one with a radiator below, even when both share the same plan shape. Measure the furthest obstruction at curtain height and below it.",
    faqs: [
      { question: "How is projection checked around a bay radiator?", answer: "Measure how far the radiator, valves, sill and handles project, then allow clearance for the chosen heading and free curtain movement." },
      { question: "Can tracks be fitted to a high ceiling?", answer: "Yes where safe access and sound structure are available. The finished curtain drop and operating method should also suit the height." },
      { question: "Do you cover Kempston and Biddenham?", answer: "Yes. Both are included within Bedford coverage." },
    ], relatedAreaSlugs: ["milton-keynes", "luton", "cambridge", "st-albans"], guideSlugs: ["how-far-from-wall-should-curtain-track-be", "curtain-tracks-for-high-ceilings"],
  },
  {
    slug: "luton", name: "Luton", region: "Bedfordshire", regionGroup: "Home Counties",
    intro: "TrackFit installs curtain tracks in Luton as part of its nationwide service, supporting Victorian housing, inter-war suburbs, modern apartments and hospitality or commercial properties. Mixed construction and busy access arrangements benefit from clear pre-installation information.",
    metaDescription: "Luton curtain-track installation for period housing, suburban homes, apartments, hotels and commercial properties by TrackFit.",
    propertyFocus: ["Victorian terraces and converted houses", "Inter-war and post-war suburban semis", "Modern apartments, new estates and extended homes"],
    challenges: ["Mixed masonry, concrete lintels and dry lining", "Bay windows with limited side returns", "Parking, airport-area access and managed commercial sites"],
    commercial: ["Hotels and serviced accommodation", "Offices, healthcare and education", "Retail, care homes and residential developments"],
    areas: ["Stopsley", "Leagrave", "Wigmore", "Bushmead", "Farley Hill", "Barton-le-Clay"],
    localNote: "For a Luton bay with short returns, decide whether curtains should stack within the bay or outside it before selecting the track. That choice changes the track route, projection and usable window area.",
    faqs: [
      { question: "Can curtains stack outside a shallow bay?", answer: "Sometimes. The wall space, radiator, furniture, heading and fixing structure determine whether extending beyond the bay is practical." },
      { question: "Can you plan hotel or serviced-accommodation installations?", answer: "Yes, from a defined room schedule, access programme, curtain loads and required track systems." },
      { question: "Do you cover Stopsley and Leagrave?", answer: "Yes. Both are included within Luton coverage." },
    ], relatedAreaSlugs: ["st-albans", "hemel-hempstead", "bedford", "milton-keynes"], guideSlugs: ["curtain-stack-back-guide", "hotel-curtain-track-installation"],
  },
  {
    slug: "chelmsford", name: "Chelmsford", region: "Essex", regionGroup: "Home Counties",
    intro: "TrackFit provides nationwide curtain-track installation in Chelmsford for Victorian terraces, suburban houses, city apartments and newer developments. Wide extensions and concrete-framed buildings require different support and access planning from older masonry homes.",
    metaDescription: "Chelmsford curtain-track fitting for terraces, suburban homes, apartments and new developments by nationwide TrackFit.",
    propertyFocus: ["Victorian terraces and older central homes", "Suburban semis and detached family houses", "City apartments, estates and wide glazed extensions"],
    challenges: ["Concrete ceilings and managed access in apartments", "Bifold doors with restricted curtain stack space", "Mixed masonry and plasterboard after refurbishment"],
    commercial: ["Offices, healthcare and education", "Hotels, hospitality and serviced accommodation", "Retail spaces and residential developments"],
    areas: ["Springfield", "Moulsham", "Great Baddow", "Broomfield", "Writtle", "Danbury"],
    localNote: "In a Chelmsford extension, check whether rooflights or a steel beam interrupt the planned ceiling fixing line. A small lateral change in track position can affect both curtain drop and clearance from door handles.",
    faqs: [
      { question: "Can tracks be fixed near a steel beam?", answer: "Potentially, but the beam, surrounding linings, services and permitted drilling method must be understood before choosing fixings." },
      { question: "Can a track span a full set of bifold doors?", answer: "Yes, with suitable support, joins where required and enough side space for the chosen curtains to stack clear." },
      { question: "Do you cover Great Baddow and Writtle?", answer: "Yes. Both are included in Chelmsford coverage." },
    ], relatedAreaSlugs: ["colchester", "basildon", "southend-on-sea", "east-london"], guideSlugs: ["fitting-curtain-tracks-under-steel-lintels", "curtain-tracks-for-bifold-doors"],
  },
  {
    slug: "colchester", name: "Colchester", region: "Essex", regionGroup: "Home Counties",
    intro: "TrackFit's nationwide service covers curtain-track installation in Colchester for historic town properties, Victorian housing, modern estates and apartments. Older masonry and conservation-sensitive interiors need a different approach from dry-lined new-build rooms.",
    metaDescription: "Colchester curtain-track installation for historic homes, Victorian housing, modern estates and apartments from TrackFit.",
    propertyFocus: ["Historic townhouses and cottages", "Victorian and Edwardian terraces", "Modern estates, apartments and detached homes"],
    challenges: ["Old masonry, uneven reveals and fragile plaster", "Conservation considerations in period interiors", "Dry lining and engineered structure in new developments"],
    commercial: ["Education, healthcare and care homes", "Hotels, hospitality and offices", "Retail spaces and residential schemes"],
    areas: ["Lexden", "Mile End", "Wivenhoe", "Stanway", "Highwoods", "Tiptree"],
    localNote: "In a Colchester period property, a window reveal may taper rather than remain parallel. Measure the intended track line directly and check curtain clearance at the tightest point, not only at the sill.",
    faqs: [
      { question: "Can a track follow an uneven period opening?", answer: "Many irregular openings can be accommodated, but the intended route, fixing points and tightest curtain clearance need to be established first." },
      { question: "Can you install in a new-build Colchester home?", answer: "Yes, subject to confirmation of backing, services, safe fixing zones and the curtain package." },
      { question: "Do you cover Wivenhoe and Stanway?", answer: "Yes. Both are included within the Colchester coverage on this page." },
    ], relatedAreaSlugs: ["chelmsford", "southend-on-sea", "cambridge", "canterbury"], guideSlugs: ["curtain-track-installation-on-uneven-walls", "fitting-curtain-tracks-to-plasterboard"],
  },
  {
    slug: "basildon", name: "Basildon", region: "Essex", regionGroup: "Home Counties",
    intro: "TrackFit installs curtain tracks across Basildon through its nationwide service, covering post-war homes, modern estates, apartments and commercial properties. Refurbishment and extensions can introduce several construction types within one otherwise consistent-looking room.",
    metaDescription: "Basildon curtain-track fitting for post-war homes, modern estates, apartments and commercial properties by TrackFit.",
    propertyFocus: ["Post-war terraces, semis and maisonettes", "Modern estates and detached family homes", "Apartments and homes with large rear extensions"],
    challenges: ["Concrete, blockwork and lightweight internal linings", "Wide patio openings and track joins", "Altered ceilings or boxed services after refurbishment"],
    commercial: ["Healthcare, education and care homes", "Offices, retail and hospitality", "Residential development and property-management work"],
    areas: ["Laindon", "Pitsea", "Vange", "Langdon Hills", "Billericay", "Wickford"],
    localNote: "Where a Basildon room has been opened into an extension, the fixing surface can change at the former external wall. Mark that transition before setting bracket spacing so a join or high-load point is not left unsupported.",
    faqs: [
      { question: "Can a track cross from the original house into an extension?", answer: "Potentially, but the changing structure, ceiling levels and suitable fixing points must be mapped across the complete track route." },
      { question: "Can you replace a track that keeps pulling away?", answer: "TrackFit can assess replacement work. The underlying cause, such as unsuitable fixings, weak plaster or insufficient support, should be addressed rather than reusing failed holes." },
      { question: "Do you cover Billericay and Wickford?", answer: "Yes. Both are included within nearby Basildon coverage." },
    ], relatedAreaSlugs: ["chelmsford", "southend-on-sea", "east-london"], guideSlugs: ["replacing-an-old-curtain-track", "curtain-track-coming-away-from-ceiling"],
  },
  {
    slug: "southend-on-sea", name: "Southend-on-Sea", region: "Essex", regionGroup: "Home Counties",
    intro: "TrackFit provides nationwide curtain-track installation across Southend-on-Sea for seafront flats, Victorian and Edwardian homes, bungalows and hospitality properties. Broad windows and coastal apartments require attention to access, light control and curtain stack-back.",
    metaDescription: "Southend-on-Sea curtain-track installation for coastal flats, period homes, bungalows and hospitality properties by TrackFit.",
    propertyFocus: ["Seafront flats and converted period buildings", "Victorian and Edwardian terraces or semis", "Bungalows, suburban homes and modern apartments"],
    challenges: ["Wide or curved windows with limited side wall", "Older plaster and masonry around bays", "Managed-flat access and busy seafront parking"],
    commercial: ["Hotels, guest accommodation and hospitality", "Healthcare, education and care homes", "Retail, offices and residential developments"],
    areas: ["Leigh-on-Sea", "Westcliff-on-Sea", "Thorpe Bay", "Shoeburyness", "Prittlewell", "Eastwood"],
    localNote: "For a Southend seafront window, check glare and privacy requirements before setting overlap. The track should give the curtains enough coverage when closed without consuming unnecessary view when open.",
    faqs: [
      { question: "Can tracks be installed across a broad seafront window?", answer: "Yes. The span, curve if any, curtain load, side overlap, fixing structure and stack-back all form part of the specification." },
      { question: "Can you work in a managed coastal apartment?", answer: "Yes, subject to contractor access, lift and parking arrangements and confirmation of the ceiling or wall construction." },
      { question: "Do you cover Leigh-on-Sea and Thorpe Bay?", answer: "Yes. Both are included within Southend-on-Sea coverage." },
    ], relatedAreaSlugs: ["basildon", "chelmsford", "colchester", "east-london"], guideSlugs: ["curtain-tracks-for-wide-windows", "curtain-stack-back-guide"],
  },
] satisfies Area[];
