import type { Area } from "../types";

export const londonAreas = [
  {
    slug: "london",
    name: "London",
    region: "Greater London",
    regionGroup: "London",
    intro: "TrackFit provides nationwide curtain-track installation throughout Greater London, supporting residential and commercial properties from central managed buildings to suburban family homes. Each installation is planned around the window, curtain load, fixing surface and the building's access requirements.",
    metaDescription: "Nationwide TrackFit curtain-track installation across Greater London for homes, apartments, offices, hotels and managed buildings.",
    propertyFocus: ["Victorian and Edwardian terraces with bays and retained cornices", "Purpose-built flats, mansion blocks and high-rise apartments", "Townhouses, suburban homes and contemporary glazed extensions"],
    challenges: ["Concrete ceilings, concealed services and restricted fixing zones", "Concierge booking, loading restrictions and limited parking", "Deep bays, decorative plaster and tight curtain stack-back space"],
    commercial: ["Hotels, serviced accommodation and hospitality interiors", "Offices, healthcare settings and education buildings", "Residential developments, retail spaces and managed portfolios"],
    areas: ["Central London", "North London", "South London", "East London", "West London"],
    localNote: "London access can shape the installation as much as the window. Confirming parking, loading, lift dimensions and concierge procedures before arrival helps protect the fitting window and avoids bringing unsuitable track lengths into a managed building.",
    faqs: [
      { question: "Can TrackFit coordinate with a London concierge or building manager?", answer: "Yes. Provide the booking rules, permitted working hours, loading arrangements and lift restrictions with the quote details so access can be considered before installation." },
      { question: "Which London curtain-track page should I use?", answer: "Use this Greater London overview if the project spans several areas, or choose the Central, North, South, East or West London page for more specific property and access guidance." },
      { question: "Can tracks be fitted to concrete apartment ceilings?", answer: "Often, yes, after checking the ceiling construction, services and permitted fixing depth. Suspended or lined ceilings need a different assessment from structural concrete." },
    ],
    relatedAreaSlugs: ["central-london", "north-london", "south-london", "east-london", "west-london"],
    guideSlugs: ["fitting-curtain-tracks-to-concrete-ceilings", "curtain-tracks-for-bay-windows"],
  },
  {
    slug: "central-london",
    name: "Central London",
    region: "Inner London",
    regionGroup: "London",
    intro: "TrackFit installs curtain tracks in Central London as part of its nationwide service, with planning suited to period townhouses, mansion flats, hotels, offices and high-specification apartments. Access, finished surfaces and restricted working arrangements are considered alongside the track itself.",
    metaDescription: "Curtain-track installation in Central London for townhouses, apartments, hotels and offices, delivered by nationwide installer TrackFit.",
    propertyFocus: ["Georgian and Victorian townhouses with tall rooms and decorative details", "Mansion flats and premium apartments in managed buildings", "Converted commercial buildings, hotels and office interiors"],
    challenges: ["High ceilings, cornices and fragile or layered plaster", "Timed loading bays, security procedures and service-lift limits", "Listed-building controls and carefully finished interiors"],
    commercial: ["Hotels, members' clubs and serviced accommodation", "Corporate offices, clinics and consulting rooms", "Retail, hospitality and premium residential developments"],
    areas: ["Westminster", "City of London", "Bloomsbury", "Marylebone", "Fitzrovia", "Mayfair"],
    localNote: "Before specifying a single long track for a central building, check the route from loading point to room. Lift cars, narrow stair turns and protected corridors may require a planned join rather than a track that cannot reach the installation space.",
    faqs: [
      { question: "Can installation be planned around Central London loading restrictions?", answer: "Yes. Share the loading-bay booking, vehicle limits and permitted working period before the visit so track lengths and equipment can be planned around the building." },
      { question: "How are high period ceilings assessed?", answer: "The fitting height, access equipment, cornice position and sound fixing material all need checking. Decorative plaster alone should not be assumed to support a loaded curtain track." },
      { question: "Does TrackFit have a Central London branch?", answer: "No local branch is claimed. Central London is covered through TrackFit's nationwide installation service, subject to the project scope and access arrangements." },
    ],
    relatedAreaSlugs: ["london", "west-london", "east-london"],
    guideSlugs: ["curtain-tracks-for-high-ceilings", "hotel-curtain-track-installation"],
  },
  {
    slug: "north-london",
    name: "North London",
    region: "Greater London",
    regionGroup: "London",
    intro: "TrackFit's nationwide installation service covers North London homes and commercial interiors, including bay-fronted terraces, converted houses, suburban semis and newer apartments. The fixing plan is matched to the building rather than assuming one bracket or mounting method suits every room.",
    metaDescription: "North London curtain-track installation for bay-fronted homes, conversions, apartments and commercial properties from nationwide TrackFit.",
    propertyFocus: ["Victorian and Edwardian terraces divided into flats", "Bay-fronted semis and detached suburban homes", "New-build apartments and mixed-use developments"],
    challenges: ["Uneven bay angles and limited returns beside built-in furniture", "Older plaster over masonry, timber or altered lintels", "Controlled parking zones and upper-floor access in conversions"],
    commercial: ["Education buildings, clinics and care settings", "Local hotels, offices and serviced accommodation", "Residential refurbishments and property developments"],
    areas: ["Enfield", "Barnet", "Haringey", "Finchley", "Highgate", "Hampstead"],
    localNote: "In a converted North London house, the ceiling visible inside one flat may conceal services, dropped construction or altered joists. Establishing what is behind the finish is more useful than copying the fixing pattern from the room below.",
    faqs: [
      { question: "Can you install a track around a North London bay window?", answer: "Yes. A bay needs accurate section measurements, suitable support around each direction change and enough return space for the chosen curtain heading." },
      { question: "Do you cover Enfield as part of North London?", answer: "Yes. Enfield is included within this North London coverage page, avoiding a second thin page for the same regional service." },
      { question: "What should I provide for a converted-flat installation?", answer: "Photographs of the full window and ceiling, approximate dimensions, access details and any known information about the ceiling or wall construction are particularly helpful." },
    ],
    relatedAreaSlugs: ["london", "central-london", "west-london", "watford"],
    guideSlugs: ["curtain-tracks-for-bay-windows", "fitting-curtain-tracks-into-timber-joists"],
  },
  {
    slug: "south-london",
    name: "South London",
    region: "Greater London",
    regionGroup: "London",
    intro: "TrackFit provides nationwide curtain-track fitting across South London, where bay-fronted houses, period conversions, town-centre apartments and suburban extensions create varied installation conditions. Croydon and Bromley are covered here as part of one useful regional hub.",
    metaDescription: "South London curtain-track installation, including Croydon and Bromley, for bays, apartments and suburban homes from TrackFit.",
    propertyFocus: ["Victorian terraces and conversions with angled or splayed bays", "Inter-war semis and detached homes across outer districts", "Apartments, town-centre developments and wide rear extensions"],
    challenges: ["Deep bay reveals, radiators and restricted curtain returns", "Mixed masonry, older plaster and previous fixing repairs", "Apartment parking, lift access and building-management approval"],
    commercial: ["Hospitality, serviced accommodation and local hotels", "Healthcare, education and care-home settings", "Offices, retail units and residential schemes"],
    areas: ["Croydon", "Bromley", "Wimbledon", "Clapham", "Dulwich", "Sutton"],
    localNote: "Many South London bays have a radiator or deep sill directly below them. Measuring only the glass width misses the projection needed for curtains to clear those obstacles and still stack away from the useful opening.",
    faqs: [
      { question: "Are Croydon and Bromley both covered from this page?", answer: "Yes. They sit within TrackFit's South London coverage and share enough property and installation considerations that separate pages would currently be unnecessarily repetitive." },
      { question: "Can a curtain track follow an angled bay?", answer: "Yes, subject to the bay shape, curtain weight and fixing surface. The bends, joins and support positions need planning from accurate measurements." },
      { question: "Can you fit tracks across wide garden doors?", answer: "Yes. The specification should allow for the full span, curtain weight, door handles, required projection and where the curtains will stack when open." },
    ],
    relatedAreaSlugs: ["london", "central-london", "west-london", "brighton-and-hove"],
    guideSlugs: ["how-to-measure-bay-window-for-curtain-track", "curtain-tracks-for-bifold-doors"],
  },
  {
    slug: "east-london",
    name: "East London",
    region: "Greater London",
    regionGroup: "London",
    intro: "TrackFit covers East London through its nationwide curtain-track installation service, working with the requirements of warehouse conversions, Victorian terraces, riverside towers and large new-build developments. Concrete construction and managed access are common planning themes, but each fixing surface still needs confirmation.",
    metaDescription: "East London curtain-track fitting for warehouse conversions, terraces, towers and new-build apartments by nationwide TrackFit.",
    propertyFocus: ["Warehouse and industrial conversions with tall or unusual openings", "Victorian terraces and maisonettes", "Riverside towers and large new-build apartment schemes"],
    challenges: ["Structural concrete, steel, dry lining and concealed services", "Floor-to-ceiling glazing with little wall space above", "Concierge access, loading zones and long routes through developments"],
    commercial: ["Creative offices, studios and flexible workspaces", "Hotels, restaurants and serviced apartments", "Healthcare, education and residential developments"],
    areas: ["Canary Wharf", "Stratford", "Hackney", "Newham", "Walthamstow", "Ilford"],
    localNote: "Full-height East London apartment glazing often makes ceiling mounting the practical starting point, but the visible ceiling may be a suspended or lined system. Confirmation of the structural build-up is essential before selecting fixings.",
    faqs: [
      { question: "Can tracks be fitted above floor-to-ceiling windows?", answer: "Often, yes. Ceiling mounting can preserve the glazing line, provided the substrate, services, projection and curtain stack-back are properly assessed." },
      { question: "What access details matter in a large East London development?", answer: "Include concierge contacts, loading instructions, lift size, parking rules, working hours and any requirement for contractor documents." },
      { question: "Do warehouse conversions need a special track?", answer: "Not automatically. The track is selected from the span, curtain load, operating method and fixing surface; unusually high or exposed openings can influence those requirements." },
    ],
    relatedAreaSlugs: ["london", "central-london", "south-london", "chelmsford"],
    guideSlugs: ["curtain-tracks-for-floor-to-ceiling-windows", "fitting-curtain-tracks-to-concrete-ceilings"],
  },
  {
    slug: "west-london",
    name: "West London",
    region: "Greater London",
    regionGroup: "London",
    intro: "TrackFit installs curtain tracks across West and North-West London as part of its nationwide service, covering period townhouses, mansion flats, suburban homes and riverside apartments. Richmond, Kingston, Harrow and Wembley are included within this broader regional page rather than being duplicated as thin borough routes.",
    metaDescription: "West London curtain-track installation, including Richmond, Kingston, Harrow and Wembley, for period homes and apartments.",
    propertyFocus: ["Period townhouses, mansion blocks and converted villas", "Riverside apartments and managed developments", "Suburban semis, detached homes and modern extensions"],
    challenges: ["Ornate cornices, delicate plaster and conservation-sensitive finishes", "Concrete apartment ceilings and restricted fixing depths", "Bay windows, wide glazing and limited stack-back beside doors"],
    commercial: ["Hotels, hospitality venues and serviced residences", "Offices, clinics, schools and care settings", "Retail interiors and residential developments"],
    areas: ["Richmond upon Thames", "Kingston upon Thames", "Harrow", "Wembley", "Ealing", "Hammersmith"],
    localNote: "A cornice can hide the wall-to-ceiling junction in West London period rooms. Before choosing wall or ceiling mounting, measure the cornice projection and identify sound structure beyond the decorative finish.",
    faqs: [
      { question: "Why are Richmond, Kingston, Harrow and Wembley covered together?", answer: "They are represented within this West and North-West London hub so the site provides useful regional guidance without creating several overlapping borough pages." },
      { question: "Can you fit tracks without damaging decorative cornices?", answer: "The aim is to avoid decorative plaster as a load-bearing fixing. The available wall or ceiling structure, safe clearances and permitted intervention must be assessed first." },
      { question: "Can a double track work in a West London apartment?", answer: "Yes where the ceiling construction, projection and available depth support two curtain layers. The voile and main curtain must each have adequate running clearance." },
    ],
    relatedAreaSlugs: ["london", "central-london", "north-london", "slough", "guildford"],
    guideSlugs: ["ceiling-vs-wall-mounted-curtain-tracks", "double-curtain-tracks-for-curtains-and-voiles"],
  },
] satisfies Area[];
