import type { Area } from "../types";

export const northMidlandsAreas = [
  {
    slug: "blackburn", name: "Blackburn", region: "Lancashire", regionGroup: "North of England",
    intro: "TrackFit provides nationwide curtain-track installation across Blackburn for stone terraces, bay-fronted semis, newer family homes and commercial properties. The service is delivered as one national company; no local office or permanent Blackburn team is claimed.",
    metaDescription: "Blackburn curtain-track installation for stone terraces, bay-fronted homes and commercial properties by nationwide TrackFit.",
    propertyFocus: ["Stone-built terraces and traditional cottages", "Victorian or Edwardian bay-fronted houses", "Suburban semis, detached homes and modern extensions"],
    challenges: ["Hard masonry beneath uneven or repaired plaster", "Deep bays, radiators and short curtain returns", "Mixed joist directions and altered ceilings in extensions"],
    commercial: ["Care homes, healthcare and education", "Offices, hospitality and retail spaces", "Residential developments and property portfolios"],
    areas: ["Darwen", "Rishton", "Great Harwood", "Oswaldtwistle", "Accrington", "Mellor"],
    localNote: "In a Blackburn stone property, the plaster depth can vary considerably across one wall. Fixing selection should account for the full distance to sound masonry rather than treating the visible surface as consistent.",
    faqs: [
      { question: "Can tracks be fitted to stone or masonry walls?", answer: "Often, yes, once the wall condition, plaster depth, safe drilling position and required curtain load have been established." },
      { question: "Can TrackFit install around a deep bay?", answer: "Yes. Each bay section, angle, return, obstruction and fixing surface needs to be measured at the intended track height." },
      { question: "Do you cover Darwen and Accrington?", answer: "Yes. Both are included within Blackburn's nearby coverage, subject to the project scope." },
    ], relatedAreaSlugs: ["manchester", "liverpool", "leeds"], guideSlugs: ["curtain-tracks-for-bay-windows", "how-far-from-wall-should-curtain-track-be"],
  },
  {
    slug: "manchester", name: "Manchester", region: "Greater Manchester", regionGroup: "North of England",
    intro: "TrackFit installs curtain tracks across Manchester through its nationwide service, for Victorian terraces, mill conversions, city apartments and commercial interiors. Concrete ceilings, large glazing and managed-building access are balanced against the curtain weight and required operation.",
    metaDescription: "Manchester curtain-track fitting for terraces, mill conversions, apartments and commercial interiors by TrackFit.",
    propertyFocus: ["Victorian terraces and bay-fronted suburban houses", "Converted mills and warehouses with tall openings", "City-centre apartments and modern glazed developments"],
    challenges: ["Concrete or steel structure and concealed services", "Concierge booking, loading and lift restrictions", "High ceilings, exposed details and long curtain drops"],
    commercial: ["Hotels, serviced apartments and hospitality", "Offices, healthcare and education", "Residential developments, retail and care settings"],
    areas: ["Didsbury", "Chorlton", "Ancoats", "Castlefield", "Salford Quays", "Prestwich"],
    localNote: "A Manchester mill conversion can have exposed concrete in one bay and a lightweight acoustic raft in the next. Treat each ceiling zone as a separate fixing condition before setting a continuous track route.",
    faqs: [
      { question: "Can you fit tracks in a Manchester mill conversion?", answer: "Yes, subject to the actual structure, services, ceiling height, track span and safe access being confirmed." },
      { question: "What information does a city-centre building need?", answer: "Provide concierge contacts, contractor rules, loading arrangements, lift dimensions, parking restrictions and permitted working hours." },
      { question: "Do you cover Didsbury and Salford Quays?", answer: "Yes. Both are represented within Greater Manchester coverage on this page." },
    ], relatedAreaSlugs: ["blackburn", "liverpool", "leeds", "sheffield"], guideSlugs: ["fitting-curtain-tracks-to-concrete-ceilings", "curtain-tracks-for-high-ceilings"],
  },
  {
    slug: "birmingham", name: "Birmingham", region: "West Midlands", regionGroup: "Midlands",
    intro: "TrackFit provides nationwide curtain-track installation across Birmingham for Victorian terraces, suburban homes, city apartments and commercial properties. The city's varied building stock calls for fixing decisions based on each room rather than a generic regional method.",
    metaDescription: "Birmingham curtain-track installation for terraces, suburban homes, apartments and commercial properties from TrackFit.",
    propertyFocus: ["Victorian terraces and inter-war bay-fronted semis", "Suburban detached homes and extended family spaces", "City apartments, loft conversions and new developments"],
    challenges: ["Mixed masonry, concrete and lightweight linings", "Wide rear glazing and bay-window projection", "Central loading, parking and multi-room access"],
    commercial: ["Hotels, healthcare and education", "Offices, hospitality and serviced accommodation", "Care homes, retail and residential developments"],
    areas: ["Edgbaston", "Harborne", "Moseley", "Sutton Coldfield", "Erdington", "Bournville"],
    localNote: "In an extended Birmingham semi, the former external wall can interrupt the ceiling structure above a long opening. Map that transition before positioning joins or brackets carrying the curtain stack.",
    faqs: [
      { question: "Can a track cross a wide opening in an extended home?", answer: "Yes where the changing structure, support positions, track joins and total curtain load are properly planned." },
      { question: "Can TrackFit support commercial room schedules?", answer: "Yes. Quantities, track types, access, programme and curtain loads are needed to assess a repeatable commercial installation." },
      { question: "Do you cover Harborne and Sutton Coldfield?", answer: "Yes. Both are included within Birmingham coverage." },
    ], relatedAreaSlugs: ["leicester", "nottingham", "gloucester", "cheltenham"], guideSlugs: ["joining-curtain-tracks", "curtain-tracks-for-bifold-doors"],
  },
  {
    slug: "leeds", name: "Leeds", region: "West Yorkshire", regionGroup: "North of England",
    intro: "TrackFit's nationwide service covers curtain-track installation across Leeds for stone terraces, Victorian villas, city apartments and commercial buildings. Deep masonry bays and concrete-framed developments need distinct fixing, projection and access plans.",
    metaDescription: "Leeds curtain-track fitting for stone homes, period bays, apartments and commercial properties by nationwide TrackFit.",
    propertyFocus: ["Stone terraces and converted traditional houses", "Victorian villas and deep bay-fronted homes", "City-centre apartments and modern developments"],
    challenges: ["Dense stone, deep plaster and uneven bay surfaces", "Concrete ceilings and managed apartment access", "Tall openings and limited stack-back around deep reveals"],
    commercial: ["Offices, education and healthcare", "Hotels, hospitality and serviced accommodation", "Care homes, retail and residential developments"],
    areas: ["Headingley", "Roundhay", "Chapel Allerton", "Horsforth", "Morley", "Pudsey"],
    localNote: "A deep Leeds stone bay can require substantial projection at the corners even when the centre section appears clear. Check the tightest return and curtain heading through every change of direction.",
    faqs: [
      { question: "Can tracks be fitted around deep stone bays?", answer: "Yes, with accurate section measurements, suitable brackets or ceiling fixing and adequate support near bends and joins." },
      { question: "Can you install in a managed Leeds apartment?", answer: "Yes, subject to construction, concierge, lift, parking and contractor requirements being supplied before the visit." },
      { question: "Do you cover Headingley and Horsforth?", answer: "Yes. Both are included within Leeds coverage." },
    ], relatedAreaSlugs: ["sheffield", "york", "manchester", "blackburn"], guideSlugs: ["curtain-tracks-for-bay-windows", "curtain-track-installation-on-uneven-walls"],
  },
  {
    slug: "liverpool", name: "Liverpool", region: "Merseyside", regionGroup: "North of England",
    intro: "TrackFit provides nationwide curtain-track installation in Liverpool for Victorian terraces, bay-fronted villas, waterfront apartments and converted commercial buildings. Older plaster, broad windows and concrete-framed developments each require a different support strategy.",
    metaDescription: "Liverpool curtain-track installation for Victorian homes, waterfront apartments and commercial interiors by TrackFit.",
    propertyFocus: ["Victorian terraces, townhouses and bay-fronted villas", "Waterfront apartments and dockside conversions", "Suburban semis, student housing and modern developments"],
    challenges: ["Older plaster, masonry and altered window heads", "Concrete apartment ceilings and concealed services", "Long windows, track joins and managed access"],
    commercial: ["Hotels, hospitality and serviced accommodation", "Education, healthcare and offices", "Student housing, retail and residential developments"],
    areas: ["Aigburth", "Allerton", "Woolton", "Georgian Quarter", "Baltic Triangle", "Crosby"],
    localNote: "For a Liverpool waterfront apartment, confirm whether the perimeter ceiling is structural or a services bulkhead. Moving the track a small distance can change both fixing safety and how the curtain clears the glazing.",
    faqs: [
      { question: "Can tracks be fitted in a dockside conversion?", answer: "Yes where the actual ceiling or wall construction, services, access and curtain load support the proposed system." },
      { question: "Can you replace a failed track in an older home?", answer: "Yes, subject to assessment. Failed holes and weak plaster should not simply receive larger versions of the same unsuitable fixing." },
      { question: "Do you cover Aigburth and Woolton?", answer: "Yes. Both are represented within Liverpool coverage." },
    ], relatedAreaSlugs: ["manchester", "blackburn", "leeds"], guideSlugs: ["replacing-an-old-curtain-track", "fitting-curtain-tracks-to-concrete-ceilings"],
  },
  {
    slug: "sheffield", name: "Sheffield", region: "South Yorkshire", regionGroup: "North of England",
    intro: "TrackFit installs curtain tracks across Sheffield through its nationwide service, covering stone terraces, Victorian villas, hillside apartments and newer family homes. Uneven masonry and changing ceiling levels make accurate setting out especially valuable.",
    metaDescription: "Sheffield curtain-track fitting for stone terraces, hillside homes, apartments and commercial properties from TrackFit.",
    propertyFocus: ["Stone terraces and traditional workers' housing", "Victorian villas and bay-fronted suburban homes", "Hillside apartments, new estates and extensions"],
    challenges: ["Hard stone beneath variable plaster depth", "Sloping or uneven ceiling and wall lines", "Deep window reveals and tall rooms"],
    commercial: ["Education, healthcare and care homes", "Hotels, offices and hospitality", "Retail, student accommodation and developments"],
    areas: ["Ecclesall", "Crookes", "Nether Edge", "Hillsborough", "Dore", "Handsworth"],
    localNote: "In a Sheffield hillside property, use a level installation datum but verify curtain drop at both ends. Following the ceiling visually can produce a track that looks aligned yet leaves uneven fabric clearance.",
    faqs: [
      { question: "Can tracks be installed where the ceiling slopes?", answer: "Often, yes. The intended visual line, sound fixings and curtain drop variation should be agreed before installation." },
      { question: "Can you fix into stone construction?", answer: "Potentially, after checking plaster depth, stone condition, drilling position and the load the fixing must carry." },
      { question: "Do you cover Ecclesall and Hillsborough?", answer: "Yes. Both are included within Sheffield coverage." },
    ], relatedAreaSlugs: ["leeds", "nottingham", "manchester", "york"], guideSlugs: ["curtain-track-installation-on-uneven-walls", "how-high-should-curtain-track-be"],
  },
  {
    slug: "nottingham", name: "Nottingham", region: "Nottinghamshire", regionGroup: "Midlands",
    intro: "TrackFit provides nationwide curtain-track installation across Nottingham for Victorian terraces, converted industrial spaces, suburban homes and city apartments. High windows, mixed masonry and managed developments require different access and fixing plans.",
    metaDescription: "Nottingham curtain-track installation for terraces, conversions, apartments and suburban homes by nationwide TrackFit.",
    propertyFocus: ["Victorian terraces and converted houses", "Lace-market and industrial conversions", "Suburban semis, apartments and new developments"],
    challenges: ["Tall windows and older or repaired plaster", "Exposed structure, steel and dry lining in conversions", "Student-building access and central parking restrictions"],
    commercial: ["Education and student accommodation", "Healthcare, offices and care homes", "Hotels, retail and residential developments"],
    areas: ["The Park", "Mapperley", "West Bridgford", "Beeston", "Sherwood", "Wollaton"],
    localNote: "In a Nottingham industrial conversion, the most visually direct track route may cross steel, brick and lining in one span. Plotting those changes first helps keep joins and high-load brackets on reliable support.",
    faqs: [
      { question: "Can tracks cross mixed materials in a conversion?", answer: "Potentially, with a fixing method and bracket layout appropriate to each verified section of the route." },
      { question: "Can you assess student-accommodation installations?", answer: "Yes. TrackFit can review room schedules, access programmes, track specifications and curtain loads for planned work." },
      { question: "Do you cover West Bridgford and Beeston?", answer: "Yes. Both are included within Nottingham coverage." },
    ], relatedAreaSlugs: ["leicester", "sheffield", "birmingham", "leeds"], guideSlugs: ["joining-curtain-tracks", "curtain-tracks-for-high-ceilings"],
  },
  {
    slug: "leicester", name: "Leicester", region: "Leicestershire", regionGroup: "Midlands",
    intro: "TrackFit installs curtain tracks in Leicester through its nationwide service, supporting Victorian terraces, bay-fronted suburban housing, city apartments and commercial interiors. Mixed building ages call for checks on lintels, plaster condition and available curtain projection.",
    metaDescription: "Leicester curtain-track fitting for terraces, bay-fronted homes, apartments and commercial interiors by TrackFit.",
    propertyFocus: ["Victorian terraces and older town housing", "Inter-war bay-fronted semis and detached homes", "City apartments, converted buildings and new estates"],
    challenges: ["Steel or concrete lintels behind shallow finishes", "Deep bays, radiators and short returns", "Mixed masonry and plasterboard after extension work"],
    commercial: ["Healthcare, education and care homes", "Offices, hospitality and retail", "Residential developments and managed properties"],
    areas: ["Clarendon Park", "Knighton", "Oadby", "Stoneygate", "Evington", "Wigston"],
    localNote: "A Leicester bay can have a solid lintel over the centre but less reliable structure around the angled returns. Each support position needs confirming rather than treating the whole bay as one material.",
    faqs: [
      { question: "Can a track be fitted beneath a hidden lintel?", answer: "Potentially, after the lintel type, services, safe drilling method and alternative wall or ceiling positions have been considered." },
      { question: "Can you fit around a radiator in a bay?", answer: "Yes where the track can provide enough projection for the curtain heading and free movement without creating an unstable bracket arrangement." },
      { question: "Do you cover Oadby and Wigston?", answer: "Yes. Both are included within Leicester coverage." },
    ], relatedAreaSlugs: ["nottingham", "birmingham", "sheffield"], guideSlugs: ["fitting-curtain-tracks-under-steel-lintels", "how-far-from-wall-should-curtain-track-be"],
  },
  {
    slug: "newcastle", name: "Newcastle", region: "Tyne and Wear", regionGroup: "North of England",
    intro: "TrackFit's nationwide service covers curtain-track installation in Newcastle for Tyneside flats, Victorian terraces, city apartments and commercial buildings. Tall sash windows, older plaster and modern concrete structures each require a distinct specification.",
    metaDescription: "Newcastle curtain-track installation for Tyneside flats, period homes, apartments and commercial buildings from TrackFit.",
    propertyFocus: ["Tyneside flats and Victorian terraces", "Period townhouses with tall sash windows", "Quayside apartments and modern developments"],
    challenges: ["High windows, cornices and older plaster", "Concrete apartment ceilings and controlled access", "Deep reveals and limited wall around traditional openings"],
    commercial: ["Hotels, hospitality and serviced accommodation", "Healthcare, education and offices", "Retail, care homes and residential developments"],
    areas: ["Jesmond", "Gosforth", "Heaton", "Ouseburn", "Fenham", "Walker"],
    localNote: "In a Tyneside flat, the ceiling construction can differ between the front and rear room because of alterations and services. Verify both rather than assuming the same joist direction throughout the property.",
    faqs: [
      { question: "Can tracks be fitted in a Tyneside flat?", answer: "Often, yes, after checking joists or other sound structure, ceiling condition, services and the intended curtain load." },
      { question: "Can you install at tall sash windows?", answer: "Yes where safe working access, suitable support and an appropriate curtain operating method can be provided." },
      { question: "Do you cover Jesmond and Heaton?", answer: "Yes. Both are included within Newcastle coverage." },
    ], relatedAreaSlugs: ["york", "leeds", "sheffield"], guideSlugs: ["fitting-curtain-tracks-into-timber-joists", "curtain-tracks-for-high-ceilings"],
  },
  {
    slug: "york", name: "York", region: "North Yorkshire", regionGroup: "North of England",
    intro: "TrackFit provides nationwide curtain-track installation in York for historic townhouses, Victorian terraces, suburban homes and hospitality properties. Older surfaces and sensitive interiors require measured intervention, while modern apartments bring different access and fixing constraints.",
    metaDescription: "York curtain-track fitting for historic homes, terraces, apartments and hospitality properties by nationwide TrackFit.",
    propertyFocus: ["Historic townhouses and compact period cottages", "Victorian and Edwardian terraces", "Suburban family homes, apartments and new developments"],
    challenges: ["Fragile plaster, uneven masonry and retained details", "Conservation-sensitive interiors and restricted central access", "Tall windows and limited curtain returns"],
    commercial: ["Hotels, visitor accommodation and hospitality", "Education, healthcare and offices", "Retail, care homes and residential developments"],
    areas: ["Bishopthorpe Road", "Fulford", "Acomb", "Heworth", "Clifton", "Haxby"],
    localNote: "In a compact York period property, access for a long track can be more restrictive than the room itself. Measure stairs and corners before deciding whether a single section or a supported join is more practical.",
    faqs: [
      { question: "Can tracks be installed in a conservation-sensitive York interior?", answer: "Potentially, once the owner has established any required permissions and a fixing route that avoids relying on decorative finishes." },
      { question: "Can a long track be supplied in joined sections?", answer: "Yes where the system allows it, with the join aligned and supported away from avoidable high-load positions." },
      { question: "Do you cover Fulford and Haxby?", answer: "Yes. Both are included within York coverage." },
    ], relatedAreaSlugs: ["leeds", "sheffield", "newcastle"], guideSlugs: ["joining-curtain-tracks", "curtain-track-installation-on-uneven-walls"],
  },
] satisfies Area[];
