import type { Area } from "../types";

export const southWestAreas = [
  {
    slug: "bristol", name: "Bristol", region: "South West England", regionGroup: "South West",
    intro: "TrackFit provides nationwide curtain-track installation across Bristol for Georgian and Victorian homes, converted industrial buildings, harbourside apartments and modern extensions. Tall rooms, retained details and broad glazing require different fixing and access strategies.",
    metaDescription: "Bristol curtain-track installation for period homes, conversions, apartments and glazed extensions by nationwide TrackFit.",
    propertyFocus: ["Georgian townhouses and Victorian terraces", "Converted warehouses, mills and harbourside apartments", "Hillside homes and contemporary glazed extensions"],
    challenges: ["High ceilings, cornices and older plaster", "Concrete or exposed structure in conversions", "Steep streets, controlled parking and long access routes"],
    commercial: ["Hotels, hospitality and serviced accommodation", "Creative offices, healthcare and education", "Retail interiors and residential developments"],
    areas: ["Clifton", "Redland", "Bedminster", "Southville", "Bishopston", "St George"],
    localNote: "A Bristol conversion may expose structure in one room and conceal it behind a suspended ceiling in the next. Record each fixing surface separately rather than applying one specification across the whole property.",
    faqs: [
      { question: "Can tracks be installed in a Bristol warehouse conversion?", answer: "Yes, subject to the actual ceiling or wall build-up, services, access and the track and curtain load required for each opening." },
      { question: "How are tall period rooms planned?", answer: "Safe access, sound structure, cornice clearance, finished curtain drop and the preferred operating method are all considered before fitting." },
      { question: "Is Bath included on the Bristol page?", answer: "No. Bath now has its own distinct page; this Bristol page focuses on the city districts and immediate coverage listed here." },
    ], relatedAreaSlugs: ["bath", "gloucester", "cheltenham", "swindon"], guideSlugs: ["curtain-tracks-for-high-ceilings", "fitting-curtain-tracks-to-concrete-ceilings"],
  },
  {
    slug: "bath", name: "Bath", region: "Somerset", regionGroup: "South West",
    intro: "TrackFit installs curtain tracks in Bath through its nationwide service, with planning suited to Georgian townhouses, converted period buildings, apartments and hospitality interiors. Listed or conservation-sensitive fabric must be respected without implying that installation permission is automatic.",
    metaDescription: "Bath curtain-track installation for Georgian homes, period conversions, apartments and hospitality properties from TrackFit.",
    propertyFocus: ["Georgian terraces, crescents and townhouses", "Converted period apartments and mews properties", "Suburban family homes and modern developments"],
    challenges: ["Tall sash windows, cornices and delicate plaster", "Listed-building or conservation constraints", "Restricted central access, stairs and protected common areas"],
    commercial: ["Hotels, spas and visitor accommodation", "Restaurants, retail and professional offices", "Healthcare, education and residential properties"],
    areas: ["Lansdown", "Widcombe", "Oldfield Park", "Bear Flat", "Bathwick", "Combe Down"],
    localNote: "In a Bath Georgian room, the visually obvious line below a cornice may be decorative plaster with no useful support. Confirm the permitted fixing zone and structure before deciding where the track should sit.",
    faqs: [
      { question: "Can tracks be installed in a listed Bath property?", answer: "Only where the owner has established any necessary permissions and an acceptable fixing method. TrackFit does not determine listed-building consent." },
      { question: "Can you fit curtains at tall sash windows?", answer: "Often, yes. The safe working height, track support, curtain drop, operating method and cornice clearance need to be considered together." },
      { question: "Do you cover Widcombe and Bathwick?", answer: "Yes. Both are included within the Bath coverage on this page." },
    ], relatedAreaSlugs: ["bristol", "salisbury", "swindon", "taunton"], guideSlugs: ["curtain-tracks-for-high-ceilings", "ceiling-vs-wall-mounted-curtain-tracks"],
  },
  {
    slug: "bournemouth", name: "Bournemouth", region: "Dorset", regionGroup: "South West",
    intro: "TrackFit provides nationwide curtain-track installation in Bournemouth for Victorian villas, converted coastal flats, modern apartments and hospitality properties. Large windows and managed buildings make projection, access and stack-back key parts of the specification.",
    metaDescription: "Bournemouth curtain-track installation for coastal villas, apartments, family homes and hospitality properties by TrackFit.",
    propertyFocus: ["Victorian and Edwardian villas or conversions", "Clifftop and town-centre apartments", "Suburban homes, bungalows and new developments"],
    challenges: ["Broad windows, bays and restricted side wall", "Concrete ceilings and dry lining in apartment blocks", "Managed access, lifts and seasonal parking pressure"],
    commercial: ["Hotels, guest accommodation and hospitality", "Care homes, healthcare and education", "Offices, retail and residential developments"],
    areas: ["Westbourne", "Boscombe", "Southbourne", "Charminster", "Winton", "Kinson"],
    localNote: "At a broad Bournemouth window, set the track position from the curtain heading and any balcony-door hardware rather than the glazing face alone. This protects movement while keeping the open view useful.",
    faqs: [
      { question: "Can you fit tracks in a clifftop apartment block?", answer: "Yes, subject to ceiling construction and the building's contractor, lift, parking and working-hour arrangements." },
      { question: "Can a track serve a wide window and balcony door?", answer: "Yes, after checking door movement, handles, span, projection, curtain weight and where the fabric can stack." },
      { question: "Do you cover Westbourne and Southbourne?", answer: "Yes. Both areas are included within Bournemouth coverage." },
    ], relatedAreaSlugs: ["poole", "salisbury", "southampton", "torquay"], guideSlugs: ["curtain-tracks-for-sliding-doors", "curtain-stack-back-guide"],
  },
  {
    slug: "poole", name: "Poole", region: "Dorset", regionGroup: "South West",
    intro: "TrackFit's nationwide installation service covers Poole homes and commercial interiors, including harbour apartments, detached coastal houses, bungalows and hospitality properties. Wide glazing and high-specification finishes require accurate clearances rather than oversized generic track choices.",
    metaDescription: "Poole curtain-track fitting for harbour apartments, coastal houses, bungalows and commercial properties from TrackFit.",
    propertyFocus: ["Harbour and marina apartments", "Detached coastal homes and modern villas", "Bungalows, suburban houses and glazed extensions"],
    challenges: ["Full-height glazing and limited wall above openings", "Concrete ceilings, recessed details and finished interiors", "Concierge access and restricted delivery routes"],
    commercial: ["Hotels, hospitality and serviced accommodation", "Healthcare, care homes and offices", "Retail spaces and residential developments"],
    areas: ["Canford Cliffs", "Parkstone", "Sandbanks", "Lilliput", "Broadstone", "Hamworthy"],
    localNote: "In a Poole harbour apartment, a recessed curtain pocket may look generous before the curtain is chosen. Confirm the heading depth, carrier drop and required double-track spacing before finalising the system.",
    faqs: [
      { question: "Can a track fit inside an existing curtain recess?", answer: "Potentially. The recess width and depth must suit the track, carriers, curtain heading, fixings and any second voile or blind layer." },
      { question: "Can you install around full-height coastal glazing?", answer: "Yes where a reliable ceiling fixing line and enough stack-back and operating clearance are available." },
      { question: "Do you cover Parkstone and Broadstone?", answer: "Yes. Both are included within Poole coverage." },
    ], relatedAreaSlugs: ["bournemouth", "salisbury", "exeter"], guideSlugs: ["recessed-curtain-tracks", "curtain-tracks-for-floor-to-ceiling-windows"],
  },
  {
    slug: "exeter", name: "Exeter", region: "Devon", regionGroup: "South West",
    intro: "TrackFit provides nationwide curtain-track fitting in Exeter for historic townhouses, Victorian terraces, student apartments, suburban homes and commercial interiors. Older walls and newer managed developments need separate access and substrate planning.",
    metaDescription: "Exeter curtain-track installation for period homes, apartments, student housing and commercial properties by TrackFit.",
    propertyFocus: ["Historic townhouses and cottages", "Victorian terraces and converted properties", "Student apartments, suburban homes and new developments"],
    challenges: ["Old masonry, uneven plaster and tall windows", "Managed access in student or city-centre buildings", "Wide glazing in modern family extensions"],
    commercial: ["Education and student accommodation", "Healthcare, offices and care homes", "Hotels, hospitality and residential developments"],
    areas: ["St Leonards", "Heavitree", "Pennsylvania", "Topsham", "Pinhoe", "Alphington"],
    localNote: "In an Exeter conversion, check whether a ceiling has been lowered to conceal services. Fixing into the visible surface without locating structural support can leave a long track dependent on lightweight framing.",
    faqs: [
      { question: "Can tracks be fitted in a converted Exeter property?", answer: "Often, yes, after confirming the altered wall or ceiling build-up and suitable support for the intended curtain load." },
      { question: "Can TrackFit assess student-accommodation work?", answer: "Yes. A room schedule, access programme, track specification and building requirements are needed to assess planned multi-room installation." },
      { question: "Do you cover Topsham and Heavitree?", answer: "Yes. Both are part of Exeter coverage." },
    ], relatedAreaSlugs: ["taunton", "torquay", "plymouth", "bristol"], guideSlugs: ["fitting-curtain-tracks-to-plasterboard", "school-curtain-track-installation"],
  },
  {
    slug: "plymouth", name: "Plymouth", region: "Devon", regionGroup: "South West",
    intro: "TrackFit installs curtain tracks across Plymouth through its nationwide service, supporting Victorian terraces, post-war housing, waterfront apartments and hospitality or healthcare buildings. Exposed glazing and concrete construction can influence mounting choice and track support.",
    metaDescription: "Plymouth curtain-track installation for terraces, post-war homes, waterfront apartments and commercial properties by TrackFit.",
    propertyFocus: ["Victorian terraces and older town housing", "Post-war semis, estates and suburban homes", "Waterfront apartments and modern developments"],
    challenges: ["Concrete ceilings and concealed services in apartments", "Wide windows exposed to strong light and coastal weather", "Older plaster, masonry and repaired openings"],
    commercial: ["Hotels, hospitality and serviced accommodation", "Healthcare, education and care settings", "Offices, retail and residential developments"],
    areas: ["The Hoe", "Mutley", "Peverell", "Mannamead", "Plymstock", "Plympton"],
    localNote: "For a Plymouth waterfront room, curtain weight and daily use matter more than exposure alone. A rigid, adequately supported track helps broad curtains operate smoothly without overloading isolated brackets.",
    faqs: [
      { question: "Can heavy curtains be fitted at a wide waterfront window?", answer: "Yes where the track, brackets, fixings and substrate are specified for the total load and frequent movement." },
      { question: "Can tracks be fixed to concrete apartment ceilings?", answer: "Often, subject to service checks, permitted fixing depth, building rules and confirmation that the visible ceiling is structural concrete." },
      { question: "Do you cover Plymstock and Plympton?", answer: "Yes. Both are included within Plymouth coverage." },
    ], relatedAreaSlugs: ["exeter", "torquay", "taunton"], guideSlugs: ["best-curtain-tracks-for-heavy-curtains", "fitting-curtain-tracks-to-concrete-ceilings"],
  },
  {
    slug: "salisbury", name: "Salisbury", region: "Wiltshire", regionGroup: "South West",
    intro: "TrackFit's nationwide curtain-track service covers Salisbury period homes, village properties, military-area housing and modern developments. Older finishes and rural access need different preparation from newer dry-lined rooms and broad extensions.",
    metaDescription: "Salisbury curtain-track fitting for period and village homes, modern developments and commercial properties from TrackFit.",
    propertyFocus: ["Medieval, Georgian and Victorian town properties", "Village cottages and detached rural homes", "Modern estates, apartments and extended houses"],
    challenges: ["Uneven masonry, old plaster and conservation considerations", "Dry lining and engineered structure in newer homes", "Rural access and long-material routes through compact buildings"],
    commercial: ["Hotels, visitor accommodation and hospitality", "Healthcare, education and care settings", "Offices, retail and residential developments"],
    areas: ["Harnham", "Laverstock", "Bemerton", "Old Sarum", "Amesbury", "Wilton"],
    localNote: "A compact Salisbury period stair can determine whether a long track reaches the room. Checking turns, landings and door widths in advance allows a planned join to be positioned away from the main curtain load.",
    faqs: [
      { question: "Can a long track be joined if access is restricted?", answer: "Yes where the selected system permits it. The join should be aligned, supported and positioned with the curtain movement and stack loads in mind." },
      { question: "Can tracks be fitted in an old cottage?", answer: "Potentially, after assessing the uneven surfaces, sound fixing material, permitted intervention and required curtain load." },
      { question: "Do you cover Amesbury and Wilton?", answer: "Yes. Both are included within Salisbury coverage." },
    ], relatedAreaSlugs: ["southampton", "winchester", "bath", "swindon"], guideSlugs: ["joining-curtain-tracks", "curtain-track-installation-on-uneven-walls"],
  },
  {
    slug: "swindon", name: "Swindon", region: "Wiltshire", regionGroup: "South West",
    intro: "TrackFit provides nationwide curtain-track installation across Swindon for railway-era terraces, post-war estates, new-build homes and commercial properties. Mixed building ages and large modern developments make substrate identification more useful than a single town-wide fixing assumption.",
    metaDescription: "Swindon curtain-track installation for period terraces, estates, new builds and commercial properties by TrackFit.",
    propertyFocus: ["Railway-era terraces and older town housing", "Post-war estates and suburban family homes", "New-build developments and broad modern extensions"],
    challenges: ["Older masonry alongside dry-lined modern construction", "Steel lintels and limited fixing zones above doors", "Repeated room types with local construction variations"],
    commercial: ["Offices, logistics and business premises", "Healthcare, education and care homes", "Hotels, retail and residential developments"],
    areas: ["Old Town", "Rodbourne", "Wroughton", "Stratton", "West Swindon", "Highworth"],
    localNote: "In a Swindon development, a steel lintel can sit directly behind a thin finish above the window. Establishing its position early prevents unsuitable drilling and may change the choice between wall and ceiling mounting.",
    faqs: [
      { question: "Can tracks be fitted where a steel lintel is present?", answer: "Potentially, using an appropriate approved method after the lintel, services and safe fixing zone have been identified." },
      { question: "Can you install tracks across several new-build rooms?", answer: "Yes, subject to a room schedule, curtain details, construction information and access being reviewed." },
      { question: "Do you cover Wroughton and Highworth?", answer: "Yes. Both are included in Swindon coverage." },
    ], relatedAreaSlugs: ["bath", "bristol", "oxford", "gloucester"], guideSlugs: ["fitting-curtain-tracks-under-steel-lintels", "what-information-needed-for-curtain-track-quote"],
  },
  {
    slug: "gloucester", name: "Gloucester", region: "Gloucestershire", regionGroup: "South West",
    intro: "TrackFit installs curtain tracks in Gloucester through its nationwide service, covering Victorian terraces, suburban homes, dockside conversions and commercial interiors. Historic masonry, modern apartment construction and wide family-room openings each need separate fitting information.",
    metaDescription: "Gloucester curtain-track fitting for Victorian homes, dockside conversions, suburbs and commercial properties from TrackFit.",
    propertyFocus: ["Victorian and Edwardian terraces", "Dockside apartments and converted industrial buildings", "Suburban homes, new estates and glazed extensions"],
    challenges: ["Old masonry, uneven plaster and deep reveals", "Concrete or steel in converted and modern apartments", "Wide doors with joins and heavy curtain stacks"],
    commercial: ["Offices, retail and hospitality", "Healthcare, education and care homes", "Residential developments and managed buildings"],
    areas: ["Longlevens", "Quedgeley", "Kingsholm", "Hucclecote", "Barnwood", "Churchdown"],
    localNote: "In a Gloucester dockside conversion, exposed brick does not automatically identify a safe fixing route; services, steelwork and lining zones may still sit behind or above the proposed track position.",
    faqs: [
      { question: "Can tracks be installed against exposed brick?", answer: "Potentially, after checking brick condition, joint positions, services, bracket type and whether wall mounting gives the required curtain projection." },
      { question: "Can you span a wide extension opening?", answer: "Yes, with a track and bracket layout suited to the length, joins, curtain weight and fixing structure." },
      { question: "Do you cover Quedgeley and Longlevens?", answer: "Yes. Both are part of Gloucester coverage." },
    ], relatedAreaSlugs: ["cheltenham", "bristol", "swindon"], guideSlugs: ["joining-curtain-tracks", "best-curtain-tracks-for-heavy-curtains"],
  },
  {
    slug: "cheltenham", name: "Cheltenham", region: "Gloucestershire", regionGroup: "South West",
    intro: "TrackFit provides nationwide curtain-track installation in Cheltenham for Regency townhouses, period apartments, suburban homes and hospitality interiors. Tall sash windows, decorative plaster and carefully finished rooms require restrained fixing and accurate setting out.",
    metaDescription: "Cheltenham curtain-track installation for Regency homes, period apartments, suburbs and hospitality properties by TrackFit.",
    propertyFocus: ["Regency terraces, villas and converted apartments", "Victorian and Edwardian family homes", "Modern developments and large suburban extensions"],
    challenges: ["Tall windows, ornate cornices and fragile plaster", "Conservation-sensitive interiors and uneven older surfaces", "Central parking, upper floors and managed common areas"],
    commercial: ["Hotels, restaurants and hospitality venues", "Professional offices, healthcare and education", "Care homes, retail and residential developments"],
    areas: ["Montpellier", "Pittville", "Leckhampton", "Charlton Kings", "Prestbury", "Hatherley"],
    localNote: "In a Cheltenham Regency room, align the track to the functional window and curtain drop rather than blindly following old cornicing, which may vary slightly across a long wall.",
    faqs: [
      { question: "Can tracks be installed below ornate cornices?", answer: "Potentially, where a sound fixing zone and enough curtain clearance exist. Decorative plaster should not be used as the structural support." },
      { question: "How are tall apartment windows approached?", answer: "Working height, access route, finished curtain drop, track operation and the wall or ceiling structure are assessed together." },
      { question: "Do you cover Pittville and Charlton Kings?", answer: "Yes. Both are included in Cheltenham coverage." },
    ], relatedAreaSlugs: ["gloucester", "bristol", "swindon"], guideSlugs: ["curtain-tracks-for-high-ceilings", "how-high-should-curtain-track-be"],
  },
  {
    slug: "taunton", name: "Taunton", region: "Somerset", regionGroup: "South West",
    intro: "TrackFit's nationwide service covers curtain-track installation in Taunton for Victorian town properties, village homes, bungalows, newer estates and commercial buildings. Rural access and mixed wall construction are considered alongside window shape and curtain load.",
    metaDescription: "Taunton curtain-track fitting for period town homes, village properties, bungalows and commercial buildings by TrackFit.",
    propertyFocus: ["Victorian terraces and older town houses", "Village cottages, farm conversions and detached homes", "Bungalows, modern estates and glazed extensions"],
    challenges: ["Old masonry, variable plaster and uneven surfaces", "Timber, steel or lightweight construction in extensions", "Rural access and transport of long track sections"],
    commercial: ["Healthcare, education and care homes", "Hotels, offices and hospitality", "Retail spaces and residential developments"],
    areas: ["Trull", "Staplegrove", "Norton Fitzwarren", "Bishop's Hull", "Comeytrowe", "Wellington"],
    localNote: "For a Taunton rural property, photograph the complete route from parking point to window. Narrow gates, stairs or ceiling beams can affect both access equipment and whether a long track should be supplied in sections.",
    faqs: [
      { question: "Can long tracks be taken into a rural or converted property?", answer: "Often, but access dimensions and turns should be checked. Joinable sections may be more practical where the route is restricted." },
      { question: "Can tracks be fitted beneath exposed beams?", answer: "Potentially, depending on the beam position, permitted fixings, curtain drop and whether the track can remain level and clear." },
      { question: "Do you cover Wellington and Trull?", answer: "Yes. Both are included within Taunton coverage." },
    ], relatedAreaSlugs: ["bristol", "bath", "exeter", "torquay"], guideSlugs: ["joining-curtain-tracks", "fitting-curtain-tracks-into-timber-joists"],
  },
  {
    slug: "torquay", name: "Torquay", region: "Devon", regionGroup: "South West",
    intro: "TrackFit provides nationwide curtain-track installation in Torquay for Victorian villas, converted coastal apartments, bungalows and hotels or guest accommodation. Curved bays, tall windows and managed access are recurring planning considerations without implying a local branch.",
    metaDescription: "Torquay curtain-track installation for Victorian villas, coastal apartments, bungalows and hospitality properties by TrackFit.",
    propertyFocus: ["Victorian villas and converted period properties", "Coastal apartments and hillside homes", "Bungalows, suburban houses and modern developments"],
    challenges: ["Curved or angled bays and tall window heads", "Older plaster, masonry and decorative finishes", "Steep access, upper floors and hospitality schedules"],
    commercial: ["Hotels, guest houses and serviced accommodation", "Care homes, healthcare and hospitality venues", "Retail, offices and residential developments"],
    areas: ["Babbacombe", "St Marychurch", "Wellswood", "Chelston", "Cockington", "Paignton"],
    localNote: "A Torquay hillside property may have different floor and ceiling levels across a bay. Measure at the proposed track height and verify the finished curtain drop at several points before ordering fabric.",
    faqs: [
      { question: "Can a track follow a curved Torquay bay?", answer: "Many track systems can be curved or formed, subject to the required radius, curtain weight, operating method and available fixing positions." },
      { question: "Can you plan fitting for a hotel or guest house?", answer: "Yes. Room quantities, access windows, track requirements and curtain loads are needed to assess a hospitality installation." },
      { question: "Do you cover Babbacombe and Paignton?", answer: "Yes. Both are included within the nearby coverage represented here." },
    ], relatedAreaSlugs: ["exeter", "plymouth", "taunton"], guideSlugs: ["curtain-tracks-for-curved-windows", "hotel-curtain-track-installation"],
  },
] satisfies Area[];
