import type { Area } from "../types";

export const southEastAreas = [
  {
    slug: "reading", name: "Reading", region: "Berkshire", regionGroup: "South East",
    intro: "TrackFit provides nationwide curtain-track installation across Reading for riverside apartments, Victorian terraces, suburban homes and commercial interiors. Modern glazing and mixed apartment construction make early checks on projection, curtain weight and fixing depth especially useful.",
    metaDescription: "Curtain-track installation in Reading for apartments, terraces, family homes and commercial interiors by nationwide TrackFit.",
    propertyFocus: ["Riverside and town-centre apartments", "Victorian terraces and established suburban homes", "New-build developments and wide glazed extensions"],
    challenges: ["Concrete, steel or dry-lined apartment construction", "Bifold doors and wide openings requiring controlled support", "Voile and blackout layers competing for projection space"],
    commercial: ["Offices and corporate interiors", "Hotels, healthcare and serviced accommodation", "Education buildings and residential developments"],
    areas: ["Caversham", "Tilehurst", "Earley", "Woodley", "Wokingham", "Theale"],
    localNote: "For a wide Reading extension, establish where the curtains will stack before setting the track length. A track can clear the doors yet still leave fabric covering part of the opening when fully drawn back.",
    faqs: [
      { question: "Can you install double tracks in a Reading apartment?", answer: "Yes, where the ceiling and available projection can support separate voile and main-curtain channels with enough clearance for both headings." },
      { question: "Do you cover Caversham, Earley and Woodley?", answer: "Yes. These areas are included within Reading coverage, subject to the project scope and installation requirements." },
      { question: "What should I measure around bifold doors?", answer: "Provide the full opening width, ceiling height, handle projection, space at both sides and photographs showing the complete route and likely curtain stack." },
    ], relatedAreaSlugs: ["slough", "high-wycombe", "oxford", "guildford"],
    guideSlugs: ["curtain-tracks-for-bifold-doors", "double-curtain-tracks-for-curtains-and-voiles"],
  },
  {
    slug: "oxford", name: "Oxford", region: "Oxfordshire", regionGroup: "South East",
    intro: "TrackFit's nationwide service covers curtain-track installation in Oxford, from historic townhouses and Victorian terraces to modern apartments and institutional interiors. Older finishes, tall rooms and controlled building access call for measured, low-assumption installation planning.",
    metaDescription: "Oxford curtain-track installation for period homes, apartments and institutional or commercial interiors from TrackFit.",
    propertyFocus: ["Historic townhouses and Victorian or Edwardian terraces", "Modern apartments and compact infill developments", "Large detached homes, extensions and converted buildings"],
    challenges: ["Fragile plaster, tall ceilings and retained decorative details", "Conservation-sensitive interiors and restricted intervention", "Cycle-heavy streets, limited parking and institutional access rules"],
    commercial: ["Education and research settings", "Hotels, offices and serviced accommodation", "Clinics, care settings and residential developments"],
    areas: ["Headington", "Summertown", "Jericho", "Cowley", "Botley", "Kidlington"],
    localNote: "In an older Oxford room, a straight visual ceiling line does not guarantee a consistent fixing surface. Previous alterations, lath-and-plaster and boxed services can require the bracket layout to respond to structure rather than symmetry alone.",
    faqs: [
      { question: "Can curtain tracks be fitted in an older Oxford property?", answer: "Often, yes, after identifying sound structure and accounting for delicate plaster, cornices or conservation constraints. Decorative finishes should not carry the curtain load." },
      { question: "Can TrackFit work with institutional access requirements?", answer: "Project access, inductions, working hours and protection requirements can be considered when supplied in advance; no guaranteed availability is implied." },
      { question: "Do you cover Headington and Summertown?", answer: "Yes. Both are included within the Oxford service area, along with the other nearby districts listed here." },
    ], relatedAreaSlugs: ["reading", "aylesbury", "swindon", "milton-keynes"],
    guideSlugs: ["curtain-tracks-for-high-ceilings", "fitting-curtain-tracks-into-timber-joists"],
  },
  {
    slug: "cambridge", name: "Cambridge", region: "Cambridgeshire", regionGroup: "South East",
    intro: "TrackFit installs curtain tracks in Cambridge through its nationwide service, supporting Victorian terraces, compact new developments, glazed family spaces and education or research interiors. The useful starting point is the actual ceiling or wall build-up, not the age label of the property.",
    metaDescription: "Cambridge curtain-track installation for terraces, new-build homes, glazed extensions and institutional interiors by TrackFit.",
    propertyFocus: ["Victorian terraces and converted houses", "New-build apartments and urban-edge developments", "Glazed extensions, garden rooms and contemporary detached homes"],
    challenges: ["Plasterboard linings concealing timber, steel or services", "Floor-to-ceiling glazing with restricted wall-mounting space", "Managed access in apartments, colleges and research buildings"],
    commercial: ["Education, research and office interiors", "Hotels, healthcare and serviced accommodation", "Residential development and property-management work"],
    areas: ["Trumpington", "Chesterton", "Romsey", "Cherry Hinton", "Newnham", "Histon"],
    localNote: "Cambridge extensions often pair a wide glazed opening with a shallow ceiling zone. Checking door movement, ventilation grilles and the true structural fixing line prevents a track being placed where fabric or hardware will clash.",
    faqs: [
      { question: "Can a track span wide glazing in a Cambridge extension?", answer: "Yes, provided the span, curtain load, joins, support spacing, projection and stack-back are designed together rather than treating length as the only requirement." },
      { question: "What information is useful for a new-build apartment?", answer: "Share ceiling and wall details from the developer if available, plus full-window photographs, dimensions, curtain information and the building's access rules." },
      { question: "Do you cover Trumpington and Chesterton?", answer: "Yes. Both districts are covered as part of the Cambridge page, subject to project scope." },
    ], relatedAreaSlugs: ["bedford", "st-albans", "milton-keynes", "colchester"],
    guideSlugs: ["curtain-tracks-for-floor-to-ceiling-windows", "fitting-curtain-tracks-to-plasterboard"],
  },
  {
    slug: "brighton-and-hove", name: "Brighton and Hove", region: "East Sussex", regionGroup: "South East",
    intro: "TrackFit provides nationwide curtain-track installation across Brighton and Hove for Regency and Victorian properties, seafront flats, suburban homes and hospitality interiors. Tall bays, decorative finishes and exposed coastal glazing each need a fitting plan that respects the building.",
    metaDescription: "Curtain-track installation across Brighton and Hove for period homes, seafront flats and hospitality properties by TrackFit.",
    propertyFocus: ["Regency terraces and tall converted townhouses", "Victorian homes with bays and retained plasterwork", "Seafront apartments, suburban houses and modern developments"],
    challenges: ["Tall windows, curved bays and decorative cornices", "Fragile plaster in subdivided period buildings", "Managed-flat access, central parking and exposed coastal openings"],
    commercial: ["Hotels, guest accommodation and hospitality venues", "Retail, offices and creative workspaces", "Healthcare, education and residential developments"],
    areas: ["Kemptown", "Seven Dials", "Preston Park", "Hove", "Portslade", "Rottingdean"],
    localNote: "A tall Brighton bay can place the track well above normal reach while offering little sound material around ornate cornicing. Confirming access equipment and the fixing zone before the visit avoids forcing a decorative feature to act as structure.",
    faqs: [
      { question: "Can tracks follow a curved or multi-sided Brighton bay?", answer: "Suitable systems can follow many bay shapes, but the geometry, curtain weight, bend radius and fixing positions must be measured before selecting the track." },
      { question: "Can you work in a converted seafront flat?", answer: "Yes, subject to access and substrate assessment. Shared entrances, upper floors, managed-building rules and fragile finishes should be described when requesting a quote." },
      { question: "Do you cover both Brighton and Hove?", answer: "Yes. This single page covers the connected city as well as the listed nearby districts, avoiding duplicate Brighton and Hove routes." },
    ], relatedAreaSlugs: ["worthing", "eastbourne", "crawley", "south-london"],
    guideSlugs: ["how-to-measure-bay-window-for-curtain-track", "curtain-tracks-for-high-ceilings"],
  },
  {
    slug: "canterbury", name: "Canterbury", region: "Kent", regionGroup: "South East",
    intro: "TrackFit's nationwide curtain-track service covers Canterbury's period homes, suburban properties, apartments and education or hospitality buildings. Irregular older surfaces and sensitive finishes are approached differently from the concrete and dry lining found in newer developments.",
    metaDescription: "Canterbury curtain-track installation for period homes, apartments, education and hospitality interiors from TrackFit.",
    propertyFocus: ["Historic townhouses and cottages", "Victorian and Edwardian terraces", "Suburban homes, student accommodation and modern apartments"],
    challenges: ["Uneven masonry, old plaster and non-square reveals", "Conservation considerations in historic interiors", "Restricted central access and occupied multi-room buildings"],
    commercial: ["Education and student accommodation", "Hotels, restaurants and visitor accommodation", "Healthcare, offices and retail premises"],
    areas: ["St Dunstan's", "Wincheap", "Hales Place", "Harbledown", "Sturry", "Blean"],
    localNote: "In a Canterbury period room, take dimensions at several points rather than assuming the opening is square. A shaped or joined track must follow the real wall line while retaining enough clearance for the curtain heading.",
    faqs: [
      { question: "Can tracks be installed on uneven walls in Canterbury?", answer: "Often, yes. The route may need careful setting out, suitable brackets or ceiling mounting, but sound fixing material must still be identified." },
      { question: "Can you support education or student-accommodation work?", answer: "TrackFit can consider planned multi-room installation where the scope, access programme and required systems are supplied for assessment." },
      { question: "Do you cover Sturry and Blean?", answer: "Yes. They are included within the nearby Canterbury coverage shown on this page." },
    ], relatedAreaSlugs: ["maidstone", "royal-tunbridge-wells", "southend-on-sea"],
    guideSlugs: ["curtain-track-installation-on-uneven-walls", "school-curtain-track-installation"],
  },
  {
    slug: "chichester", name: "Chichester", region: "West Sussex", regionGroup: "South East",
    intro: "TrackFit covers Chichester through its nationwide curtain-track installation service, with guidance for period townhouses, village homes, coastal properties and newer developments. The specification can account for delicate finishes, wide glazing and rooms where the fixing line is not immediately visible.",
    metaDescription: "Chichester curtain-track installation for period, village and coastal homes plus commercial properties from TrackFit.",
    propertyFocus: ["Georgian and Victorian townhouses", "Village cottages and detached rural-edge homes", "Coastal apartments, newer estates and glazed extensions"],
    challenges: ["Older plaster, masonry and conservation-sensitive details", "Wide doors and limited curtain stack space", "Access planning for central, rural and coastal properties"],
    commercial: ["Hotels, restaurants and visitor accommodation", "Healthcare, education and care homes", "Retail spaces, offices and residential schemes"],
    areas: ["Fishbourne", "Bosham", "Tangmere", "Lavant", "Selsey", "The Witterings"],
    localNote: "Coastal glazing around Chichester can be wide while wall space at each side is limited. Stack-back should be calculated from the finished curtain heading so the fabric does not obstruct doors or the main view.",
    faqs: [
      { question: "Can tracks be fitted across wide coastal glazing?", answer: "Yes, after checking span, curtain load, available structure, door movement, projection and how much side space the open curtains require." },
      { question: "How are delicate period finishes protected?", answer: "The fixing strategy should avoid relying on decorative plaster, with access, drilling and room protection planned around the known condition of the interior." },
      { question: "Do you cover Bosham and the Witterings?", answer: "Yes. These nearby areas are included within Chichester coverage, subject to the project details." },
    ], relatedAreaSlugs: ["portsmouth", "worthing", "winchester"],
    guideSlugs: ["curtain-stack-back-guide", "curtain-tracks-for-wide-windows"],
  },
  {
    slug: "crawley", name: "Crawley", region: "West Sussex", regionGroup: "South East",
    intro: "TrackFit installs curtain tracks in Crawley as part of its nationwide service, covering post-war neighbourhoods, modern family homes, apartments and business or hospitality properties. Practical access and repeatable fixing plans are important where projects include several similar rooms.",
    metaDescription: "Crawley curtain-track fitting for family homes, apartments, hotels, offices and developments by nationwide TrackFit.",
    propertyFocus: ["Post-war terraces, semis and neighbourhood housing", "Modern detached homes and new-build estates", "Town-centre apartments and extended family homes"],
    challenges: ["Concrete lintels and mixed wall construction", "Bifold-door openings in renovated homes", "Managed access and parking around apartments or business sites"],
    commercial: ["Hotels and serviced accommodation", "Offices, logistics and business-park interiors", "Healthcare, education and residential developments"],
    areas: ["Three Bridges", "Ifield", "Pound Hill", "Maidenbower", "Tilgate", "Broadfield"],
    localNote: "Where several Crawley rooms use the same window type, confirm the substrate in each room rather than copying the first fixing pattern. Extensions and later alterations can change the construction behind an identical-looking finish.",
    faqs: [
      { question: "Can TrackFit install tracks in several rooms during one project?", answer: "Yes, subject to scope. Provide a room schedule with dimensions, curtain details and photographs so repeated and exceptional openings can be distinguished." },
      { question: "Can you fit above a concrete lintel?", answer: "Potentially. The proposed fixing line and lintel construction need assessment; services and safe drilling depths must also be considered." },
      { question: "Do you cover Three Bridges and Pound Hill?", answer: "Yes. Both are part of the Crawley coverage represented on this page." },
    ], relatedAreaSlugs: ["guildford", "brighton-and-hove", "royal-tunbridge-wells"],
    guideSlugs: ["fitting-curtain-tracks-under-steel-lintels", "what-information-needed-for-curtain-track-quote"],
  },
  {
    slug: "eastbourne", name: "Eastbourne", region: "East Sussex", regionGroup: "South East",
    intro: "TrackFit provides nationwide curtain-track fitting in Eastbourne for Victorian and Edwardian houses, seafront flats, suburban homes and visitor accommodation. Tall windows, bays and exposed glazing need suitable support without treating older plaster as a structural fixing surface.",
    metaDescription: "Eastbourne curtain-track installation for period homes, seafront flats, hotels and suburban properties by TrackFit.",
    propertyFocus: ["Victorian and Edwardian villas or terraces", "Seafront flats and converted period buildings", "Bungalows, suburban semis and modern apartments"],
    challenges: ["Tall bays, deep reveals and high fixing positions", "Old or repaired plaster over masonry", "Managed access and limited parking near central or seafront buildings"],
    commercial: ["Hotels, guest accommodation and hospitality", "Care homes, healthcare and community settings", "Retail, offices and residential developments"],
    areas: ["Meads", "Old Town", "Hampden Park", "Langney", "Sovereign Harbour", "Polegate"],
    localNote: "Eastbourne seafront rooms can combine a tall opening with strong light and limited side wall. Plan lining coverage and stack-back together so the selected track supports both privacy and a useful clear opening.",
    faqs: [
      { question: "Can tracks be fitted in a tall Eastbourne bay?", answer: "Yes, subject to accurate bay measurements, safe working access, a suitable fixing zone and a track capable of supporting the curtain through each bend." },
      { question: "Do you install in care or hospitality properties?", answer: "TrackFit can assess planned commercial and multi-room work without implying any existing local contract or guaranteed programme." },
      { question: "Is Sovereign Harbour covered?", answer: "Yes. Sovereign Harbour is included within Eastbourne coverage, with apartment access details considered during quoting." },
    ], relatedAreaSlugs: ["brighton-and-hove", "royal-tunbridge-wells", "worthing"],
    guideSlugs: ["curtain-tracks-for-high-ceilings", "care-home-curtain-track-installation"],
  },
  {
    slug: "guildford", name: "Guildford", region: "Surrey", regionGroup: "South East",
    intro: "TrackFit's nationwide installation service covers Guildford homes and commercial properties, from period terraces and hillside houses to executive apartments and large glazed extensions. Uneven levels, valuable finishes and long door spans benefit from careful survey information.",
    metaDescription: "Guildford curtain-track installation for period homes, apartments, extensions and commercial properties from TrackFit.",
    propertyFocus: ["Period terraces and town-centre cottages", "Hillside detached homes and suburban family houses", "Executive apartments and large contemporary extensions"],
    challenges: ["Sloping or uneven surfaces and older plaster", "Long glazed spans with heavy curtain packages", "Central access restrictions and managed apartment entry"],
    commercial: ["Offices, professional services and clinics", "Hotels, education and serviced accommodation", "Residential developments and care settings"],
    areas: ["Merrow", "Burpham", "Stoughton", "Onslow Village", "Shalford", "Worplesdon"],
    localNote: "On a wide Guildford rear extension, bracket spacing should respond to curtain weight and track joins, not just the door mullions below. The track needs independent, reliable support across the full run.",
    faqs: [
      { question: "Can you install a heavy-curtain track across wide doors?", answer: "Yes, where the selected track, support spacing, joins and fixing structure are suitable for the combined curtain weight and operating pattern." },
      { question: "What if the ceiling is visibly uneven?", answer: "The track route and fixing points can be planned from the real surface, but significant irregularity or uncertain structure may require additional survey detail." },
      { question: "Do you cover Merrow and Burpham?", answer: "Yes. Both are included in the nearby Guildford coverage on this page." },
    ], relatedAreaSlugs: ["woking", "reading", "crawley", "west-london"],
    guideSlugs: ["best-curtain-tracks-for-heavy-curtains", "curtain-track-installation-on-uneven-walls"],
  },
  {
    slug: "maidstone", name: "Maidstone", region: "Kent", regionGroup: "South East",
    intro: "TrackFit installs curtain tracks across Maidstone through its nationwide service, supporting older town properties, suburban family homes, apartments and commercial buildings. Mixed construction and altered openings mean photographs of the whole wall are more useful than a close-up of the window alone.",
    metaDescription: "Maidstone curtain-track fitting for period properties, family homes, apartments and commercial interiors by TrackFit.",
    propertyFocus: ["Victorian terraces and older town houses", "Suburban semis, detached homes and bungalows", "Modern apartments and new housing developments"],
    challenges: ["Mixed masonry, plasterboard and concrete lintels", "Bay windows altered during refurbishment", "Parking and loading around central or managed buildings"],
    commercial: ["Healthcare, education and care homes", "Offices, hotels and hospitality", "Retail spaces and residential developments"],
    areas: ["Allington", "Bearsted", "Penenden Heath", "Loose", "Barming", "Aylesford"],
    localNote: "If a Maidstone bay has been replastered or insulated, the visible reveal may conceal the original masonry line. Fixing length and bracket position should be based on confirmed construction rather than the thickness of the new finish.",
    faqs: [
      { question: "Can tracks be fitted after a bay has been replastered?", answer: "Often, yes, but the new finish and the sound material behind it must be understood so the fixing does not rely on plaster alone." },
      { question: "Can you plan installations for care or healthcare rooms?", answer: "Yes, subject to the required track type, room schedule, access, hygiene and programme information being assessed in advance." },
      { question: "Do you cover Bearsted and Aylesford?", answer: "Yes. Both are represented within Maidstone's nearby coverage." },
    ], relatedAreaSlugs: ["canterbury", "royal-tunbridge-wells"],
    guideSlugs: ["fitting-curtain-tracks-to-plasterboard", "healthcare-curtain-track-installation"],
  },
  {
    slug: "royal-tunbridge-wells", name: "Royal Tunbridge Wells", region: "Kent", regionGroup: "South East",
    intro: "TrackFit provides nationwide curtain-track installation in Royal Tunbridge Wells for Regency and Victorian properties, bay-fronted family homes, apartments and hospitality spaces. Decorative interiors and non-standard bays require careful measuring without assuming every period window shares the same geometry.",
    metaDescription: "Royal Tunbridge Wells curtain-track installation for period homes, bays, apartments and hospitality properties by TrackFit.",
    propertyFocus: ["Regency and Victorian terraces or villas", "Edwardian and inter-war bay-fronted homes", "Apartments, converted buildings and modern developments"],
    challenges: ["Decorative cornices, fragile plaster and tall rooms", "Multi-angle bays and deep window reveals", "Conservation-sensitive finishes and central access"],
    commercial: ["Hotels, spas and hospitality venues", "Professional offices, clinics and retail", "Education, care and residential developments"],
    areas: ["Southborough", "Rusthall", "Pembury", "Langton Green", "Speldhurst", "Bidborough"],
    localNote: "A Tunbridge Wells bay may change angle from sill to ceiling because of old finishes or later repairs. Measurements taken at the intended track height are more reliable than transferring dimensions from the window board.",
    faqs: [
      { question: "How should a period bay be measured?", answer: "Record each section and angle at the planned track height, plus projections, returns and obstructions. Photographs should show the complete ceiling and both sides of the bay." },
      { question: "Can a track be installed near decorative cornicing?", answer: "Potentially, after identifying a safe route and sound structure that does not treat the decorative cornice itself as a fixing point." },
      { question: "Do you cover Southborough and Pembury?", answer: "Yes. Both locations are included within this Royal Tunbridge Wells coverage page." },
    ], relatedAreaSlugs: ["maidstone", "crawley", "eastbourne", "canterbury"],
    guideSlugs: ["how-to-measure-bay-window-for-curtain-track", "ceiling-vs-wall-mounted-curtain-tracks"],
  },
  {
    slug: "slough", name: "Slough", region: "Berkshire", regionGroup: "South East",
    intro: "TrackFit's nationwide service includes curtain-track installation in Slough for suburban homes, apartments, hotels, offices and development work. Modern concrete construction, wide glazing and multi-room programmes each require clear fixing and access information before installation.",
    metaDescription: "Slough curtain-track installation for homes, apartments, hotels, offices and developments by nationwide TrackFit.",
    propertyFocus: ["Inter-war and post-war suburban housing", "Modern apartments and mixed-use developments", "Detached homes with extended or glazed living spaces"],
    challenges: ["Concrete ceilings, steel lintels and dry-lined walls", "Wide patio openings and double-track projection", "Managed-building access and repeatable multi-room layouts"],
    commercial: ["Hotels and serviced accommodation", "Offices, business parks and healthcare", "Residential developments, education and care settings"],
    areas: ["Langley", "Cippenham", "Wexham", "Colnbrook", "Burnham", "Datchet"],
    localNote: "For repeated Slough apartment layouts, keep one verified fixing specification but check each room for ceiling services, boxed zones and finish changes. A standard room type does not guarantee an identical substrate everywhere.",
    faqs: [
      { question: "Can you quote for multiple similar apartment rooms?", answer: "Yes. A room schedule, representative photographs and construction information help identify the repeatable work and any exceptional openings." },
      { question: "Can TrackFit install in hotels or offices?", answer: "Commercial work can be assessed from the programme, access, room quantities, curtain loads and required track specification." },
      { question: "Do you cover Langley and Cippenham?", answer: "Yes. Both are included within the Slough coverage described here." },
    ], relatedAreaSlugs: ["reading", "west-london", "high-wycombe", "st-albans"],
    guideSlugs: ["hotel-curtain-track-installation", "fitting-curtain-tracks-to-concrete-ceilings"],
  },
  {
    slug: "southampton", name: "Southampton", region: "Hampshire", regionGroup: "South East",
    intro: "TrackFit provides nationwide curtain-track installation across Southampton for Victorian terraces, waterfront apartments, suburban houses and commercial or hospitality buildings. Managed access, concrete construction and broad glazed openings are considered alongside the curtain specification.",
    metaDescription: "Southampton curtain-track fitting for terraces, waterfront apartments, family homes and commercial properties from TrackFit.",
    propertyFocus: ["Victorian terraces and converted houses", "Waterfront and city-centre apartments", "Suburban family homes and contemporary extensions"],
    challenges: ["Concrete apartment ceilings and concealed building services", "Balcony doors, wide glazing and limited side returns", "Port-city access, parking and concierge arrangements"],
    commercial: ["Hotels, hospitality and serviced accommodation", "Healthcare, education and care homes", "Offices, retail and residential developments"],
    areas: ["Ocean Village", "Portswood", "Shirley", "Bitterne", "Woolston", "Bassett"],
    localNote: "In a Southampton waterfront apartment, verify whether the ceiling edge contains curtain recesses, ventilation or concealed services. The cleanest visual line is not always the safest drilling line.",
    faqs: [
      { question: "Can tracks be ceiling-mounted in a waterfront apartment?", answer: "Often, yes, once the ceiling type, permitted fixing depth, services, curtain weight and building-management requirements have been confirmed." },
      { question: "Can you fit a track across balcony doors?", answer: "Yes. Door handles, opening movement, track projection, curtain stack-back and the full span all need to be measured." },
      { question: "Do you cover Ocean Village and Portswood?", answer: "Yes. Both areas are included within Southampton coverage." },
    ], relatedAreaSlugs: ["portsmouth", "winchester", "bournemouth", "salisbury"],
    guideSlugs: ["curtain-tracks-for-sliding-doors", "fitting-curtain-tracks-to-concrete-ceilings"],
  },
  {
    slug: "portsmouth", name: "Portsmouth", region: "Hampshire", regionGroup: "South East",
    intro: "TrackFit installs curtain tracks in Portsmouth through its nationwide service, supporting compact terraces, seafront apartments, suburban homes and hospitality or naval-city commercial interiors. Narrow rooms and limited parking make accurate preparation particularly valuable.",
    metaDescription: "Portsmouth curtain-track installation for terraces, seafront flats, family homes and commercial interiors by TrackFit.",
    propertyFocus: ["Compact Victorian and Edwardian terraces", "Seafront flats and converted period buildings", "Post-war homes, apartments and modern developments"],
    challenges: ["Narrow bays, radiators and limited curtain returns", "Older plaster, masonry and altered lintels", "Dense-street parking and managed apartment access"],
    commercial: ["Hotels, hospitality and serviced accommodation", "Healthcare, education and offices", "Retail spaces, care homes and residential developments"],
    areas: ["Southsea", "Old Portsmouth", "North End", "Copnor", "Hilsea", "Drayton"],
    localNote: "In a compact Portsmouth room, track projection must clear both the window hardware and any radiator while preserving usable floor space. A shallow-looking wall bracket can still place the curtain too close to move freely.",
    faqs: [
      { question: "Can a track be fitted in a narrow Southsea bay?", answer: "Yes, subject to the bay geometry, curtain heading, radiator projection and availability of sound wall or ceiling fixings." },
      { question: "What helps with installation on a street with limited parking?", answer: "Provide parking restrictions, property access and the route to the room when requesting a quote so equipment and track lengths can be planned." },
      { question: "Do you cover Southsea and Hilsea?", answer: "Yes. Both are part of the Portsmouth coverage shown here." },
    ], relatedAreaSlugs: ["southampton", "chichester", "winchester"],
    guideSlugs: ["how-far-from-wall-should-curtain-track-be", "curtain-tracks-for-small-windows"],
  },
  {
    slug: "winchester", name: "Winchester", region: "Hampshire", regionGroup: "South East",
    intro: "TrackFit's nationwide curtain-track service covers Winchester period homes, village properties, modern family houses and commercial interiors. Older masonry, sensitive finishes and high-value rooms benefit from a fixing plan based on confirmed structure and restrained intervention.",
    metaDescription: "Winchester curtain-track installation for period, village and modern homes plus commercial properties from TrackFit.",
    propertyFocus: ["Georgian and Victorian townhouses", "Village cottages and converted rural buildings", "Modern detached homes and glazed extensions"],
    challenges: ["Old masonry, lime or fragile plaster and uneven reveals", "Conservation-sensitive interiors and decorative details", "Long glazed openings with limited stack-back"],
    commercial: ["Hotels, hospitality and visitor accommodation", "Education, healthcare and professional offices", "Care settings and residential developments"],
    areas: ["St Cross", "Fulflood", "Weeke", "Kings Worthy", "Twyford", "Alresford"],
    localNote: "Before drilling in a Winchester period room, distinguish a decorative lining from the masonry or timber that can actually carry the load. Longer fixings are not a substitute for knowing what lies behind the finish.",
    faqs: [
      { question: "Can tracks be fitted in a conservation-sensitive interior?", answer: "Potentially, but the property constraints and permitted intervention must be established first. TrackFit does not provide planning or listed-building consent advice." },
      { question: "Can you install across a large rural extension?", answer: "Yes, subject to span, access, curtain weight, structural fixing points and clearance around doors or glazing." },
      { question: "Do you cover Kings Worthy and Twyford?", answer: "Yes. Both sit within the nearby Winchester coverage on this page." },
    ], relatedAreaSlugs: ["southampton", "portsmouth", "salisbury", "chichester"],
    guideSlugs: ["fitting-curtain-tracks-into-timber-joists", "curtain-tracks-for-wide-windows"],
  },
  {
    slug: "woking", name: "Woking", region: "Surrey", regionGroup: "South East",
    intro: "TrackFit provides nationwide curtain-track installation in Woking for suburban houses, apartments, new-build developments and commercial properties. Wide family-room glazing and managed town-centre buildings require different access and fixing approaches.",
    metaDescription: "Woking curtain-track fitting for suburban homes, apartments, new builds and commercial properties by TrackFit.",
    propertyFocus: ["Suburban semis and detached family homes", "Town-centre apartments and new-build developments", "Extended homes with bifold or sliding doors"],
    challenges: ["Concrete ceilings and dry-lined walls in apartments", "Wide door spans and heavy curtain stacks", "Building-management access and commuter-centre parking"],
    commercial: ["Offices, hotels and serviced accommodation", "Healthcare, education and care homes", "Retail interiors and residential developments"],
    areas: ["Horsell", "Knaphill", "Goldsworth Park", "Pyrford", "West Byfleet", "Brookwood"],
    localNote: "For a Woking bifold-door project, measure the side space after allowing for sockets, cabinets and door controls. The required track length depends on where the curtains can physically stack, not only the glazed width.",
    faqs: [
      { question: "Can a curtain track extend beyond wide bifold doors?", answer: "Yes, where there is sound fixing structure and enough unobstructed side space. Extending the track can improve stack-back and preserve more of the opening." },
      { question: "Can you install in a managed Woking apartment?", answer: "Yes, subject to the ceiling construction and the building's booking, insurance, parking, lift and working-hour requirements." },
      { question: "Do you cover Horsell and Knaphill?", answer: "Yes. Both are included within Woking coverage." },
    ], relatedAreaSlugs: ["guildford", "reading", "west-london", "crawley"],
    guideSlugs: ["how-far-should-curtain-track-extend-past-window", "curtain-tracks-for-bifold-doors"],
  },
  {
    slug: "worthing", name: "Worthing", region: "West Sussex", regionGroup: "South East",
    intro: "TrackFit installs curtain tracks across Worthing through its nationwide service, for seafront flats, period houses, bungalows, suburban homes and visitor accommodation. Bays and broad coastal windows need support, projection and stack-back to be planned as one system.",
    metaDescription: "Worthing curtain-track installation for seafront flats, period homes, bungalows and commercial properties by TrackFit.",
    propertyFocus: ["Seafront apartments and converted period buildings", "Victorian or Edwardian terraces and semis", "Bungalows, suburban homes and newer developments"],
    challenges: ["Broad windows, bays and limited side wall", "Older plaster or masonry around altered openings", "Apartment access and parking near central or seafront properties"],
    commercial: ["Hotels, guest accommodation and hospitality", "Care homes, healthcare and community buildings", "Retail, offices and residential developments"],
    areas: ["West Worthing", "Broadwater", "Goring-by-Sea", "Durrington", "Tarring", "Findon"],
    localNote: "A broad Worthing window may need more side overlap for light control while also having little room for open curtains. Recording both requirements early prevents the track length solving one problem and worsening the other.",
    faqs: [
      { question: "Can tracks be planned for light control at a wide coastal window?", answer: "Yes. Side overlap, centre closure, curtain fullness and stack-back can be considered with the track length and projection." },
      { question: "Can you fit in a bungalow with uncertain ceiling construction?", answer: "Potentially. Loft access or construction information can help locate suitable structure rather than assuming the visible ceiling finish is load-bearing." },
      { question: "Do you cover Goring-by-Sea and Tarring?", answer: "Yes. Both are included in the nearby Worthing coverage." },
    ], relatedAreaSlugs: ["brighton-and-hove", "chichester", "eastbourne"],
    guideSlugs: ["how-far-should-curtain-track-extend-past-window", "fitting-curtain-tracks-into-timber-joists"],
  },
] satisfies Area[];
