create table if not exists public.trackfit_bay_plans (
 id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references auth.users(id), lead_id uuid references public.trackfit_enquiries(id) on delete set null,
 job_reference text not null default '', customer_name text not null default '', postcode text not null default '', room text not null default '', shape_type text not null default '2_bend_angled_bay', measurements jsonb not null, calculated_geometry jsonb not null, track_system text not null check(track_system in('KS','CS')), machine_config jsonb not null, spring_back_settings jsonb not null, working_direction text not null, track_details jsonb not null, warnings jsonb not null default '[]', validation_status text not null check(validation_status in('pass','check','fail')), override_reason text, installer_notes text, workshop_notes text, archived_at timestamptz
);
create index if not exists trackfit_bay_plans_created_idx on public.trackfit_bay_plans(created_at desc);create index if not exists trackfit_bay_plans_lead_idx on public.trackfit_bay_plans(lead_id);
create or replace function public.trackfit_touch_bay_plan() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now();return new;end;$$;
drop trigger if exists trackfit_bay_plans_touch on public.trackfit_bay_plans;create trigger trackfit_bay_plans_touch before update on public.trackfit_bay_plans for each row execute function public.trackfit_touch_bay_plan();
alter table public.trackfit_bay_plans enable row level security;revoke all on public.trackfit_bay_plans from anon;grant select,insert,update,delete on public.trackfit_bay_plans to authenticated;
drop policy if exists "TrackFit admins manage bay plans" on public.trackfit_bay_plans;create policy "TrackFit admins manage bay plans" on public.trackfit_bay_plans for all to authenticated using(public.is_trackfit_admin()) with check(public.is_trackfit_admin() and created_by=auth.uid());
