export type GalleryImage = {
  src: string;
  alt: string;
  title: string;
  credit?: string;
  sourceUrl?: string;
  category: "Residential" | "Bay and curved" | "Wave curtains" | "Motorised" | "Hospitality" | "Commercial" | "System detail";
  format?: "wide" | "tall" | "square";
};

export const galleryImages: GalleryImage[] = [
  {
    src: "/images/gallery/forest/curved-office-divider.webp",
    alt: "Curved ceiling curtain track creating a soft room divider in a bright office",
    title: "Curved room divider",
    category: "Bay and curved",
    format: "wide",
  },
  {
    src: "/images/gallery/bay-windows/bridges-bespoke-bay.webp",
    alt: "Elegant curved bay window with floor length neutral curtains between each window section",
    title: "Full length curtains across a curved bay",
    credit: "Image source: Bridges Interiors",
    sourceUrl: "https://bridgesinteriors.com/curtains",
    category: "Bay and curved",
    format: "wide",
  },
  {
    src: "/images/gallery/bay-windows/gardinskinner-white-wave-bay.webp",
    alt: "White wave curtains following a rounded bay window on a ceiling mounted curved track",
    title: "White wave curtains around a rounded bay",
    credit: "Image source: Gardinskinner.dk",
    sourceUrl: "https://gardinskinner.dk/blogs/guides-gardinsyning-gardinskinner/bukket-gardinskinner-til-karnap",
    category: "Bay and curved",
    format: "tall",
  },
  {
    src: "/images/gallery/bay-windows/sanmar-curved-window-curtains.webp",
    alt: "Layered beige curtains following a large curved window with concealed ceiling tracks",
    title: "Layered curtains on a sweeping curve",
    credit: "Image source: Cortinas Sanmar",
    sourceUrl: "https://cortinassanmar.es/cortinas-a-medida-para-ventanales-curvos/",
    category: "Bay and curved",
    format: "wide",
  },
  {
    src: "/images/gallery/bay-windows/silent-gliss-bay-curtains.webp",
    alt: "White curtains framing a compact traditional bay window with a yellow chair",
    title: "Discreet track in a compact bay",
    credit: "Image source: Silent Gliss",
    sourceUrl: "https://www.silentgliss.co.uk/engb/products/view/curtain-systems/",
    category: "Bay and curved",
    format: "tall",
  },
  {
    src: "/images/gallery/bay-windows/eze-square-bay-curtains.webp",
    alt: "Square bay window with pinch pleat curtains stacked neatly beyond the glass",
    title: "Pinch pleat curtains in a square bay",
    credit: "Image source: Ezecurtains",
    sourceUrl: "https://ezecurtains.co.uk/best-curtain-tracks-for-bay-windows/bay-window-curtain-tracks/",
    category: "Bay and curved",
    format: "wide",
  },
  {
    src: "/images/gallery/bay-windows/gardinskinner-blue-wave-bay.webp",
    alt: "Blue wave curtains and white sheers following an ornate curved ceiling line",
    title: "Blue wave curtains on a curved track",
    credit: "Image source: Gardinskinner.dk",
    sourceUrl: "https://gardinskinner.dk/blogs/guides-gardinsyning-gardinskinner/bukket-gardinskinner-til-karnap",
    category: "Bay and curved",
    format: "wide",
  },
  {
    src: "/images/gallery/bay-windows/etikk-ceiling-curved-track.webp",
    alt: "Close view of a ceiling mounted track curving around a bay window with white curtains",
    title: "Ceiling track following the bay line",
    credit: "Image source: Etikk",
    sourceUrl: "https://etikk.dk/blog/hvilke-gardiner-skal-jeg-vaelge-til-min-karnap",
    category: "Bay and curved",
    format: "tall",
  },
  {
    src: "/images/gallery/bay-windows/curtarra-curved-track.webp",
    alt: "Close view of neutral curtains running smoothly around a tightly curved ceiling track",
    title: "Tight bend curtain track detail",
    credit: "Image source: Curtarra",
    sourceUrl: "https://www.curtarra.com/pages/solution/bay-window-curtain-design",
    category: "Bay and curved",
    format: "square",
  },
  {
    src: "/images/gallery/bay-windows/gordon-smith-curved-track.webp",
    alt: "White track precisely curved around a rounded bay window before the curtains are hung",
    title: "Bespoke track shaped to a rounded bay",
    credit: "Image source: Gordon Smith",
    sourceUrl: "https://www.gordonsmithmalvern.co.uk/latest-projects/Curved%20bay%20curtains/99/latest-projects/Curved-bay-curtains/99/",
    category: "Bay and curved",
    format: "square",
  },
  {
    src: "/images/gallery/bay-windows/nustyle-pinch-pleat-bay.webp",
    alt: "Grey pinch pleat curtains tied back around a five sided bay window with sheer curtains",
    title: "Pinch pleat and sheer bay treatment",
    credit: "Image source: Nu Style Curtains",
    sourceUrl: "https://www.nustylecurtains.com.au/single-post/how-to-use-ready-made-curtains-on-a-bay-window",
    category: "Bay and curved",
    format: "wide",
  },
  {
    src: "/images/gallery/forest/black-track-interior.webp",
    alt: "Black curtain tracks and full height curtains in a contemporary interior",
    title: "Black track interior",
    category: "Residential",
    format: "wide",
  },
  {
    src: "/images/showcase/forest/hotel-curtains.webp",
    alt: "Layered full height curtains in a hospitality dining space",
    title: "Layered hospitality curtains",
    category: "Hospitality",
    format: "wide",
  },
  {
    src: "/images/gallery/forest/dubai-hotel-room.webp",
    alt: "Floor to ceiling hotel curtains fitted to a heavy duty track",
    title: "Hotel room track",
    category: "Hospitality",
    format: "wide",
  },
  {
    src: "/images/showcase/forest/office-curtains.webp",
    alt: "Curtains dividing a flexible commercial interior",
    title: "Flexible commercial space",
    category: "Commercial",
    format: "wide",
  },
  {
    src: "/images/showcase/forest/dsxl-hotel.webp",
    alt: "Full height curtains installed in a contemporary hotel room",
    title: "Full height hotel curtains",
    category: "Hospitality",
  },
  {
    src: "/images/gallery/forest/design-series-black.webp",
    alt: "Black design curtain track installed against a dark ceiling",
    title: "Black design series",
    category: "System detail",
  },
  {
    src: "/images/gallery/forest/cs-black-track.webp",
    alt: "Black Forest CS curtain track with wave curtain heading",
    title: "Black CS track",
    category: "Wave curtains",
  },
  {
    src: "/images/gallery/forest/shuttle-black.webp",
    alt: "Black Forest Shuttle motor and curtain track detail",
    title: "Black motorised finish",
    category: "Motorised",
  },
  {
    src: "/images/gallery/forest/crs-black.webp",
    alt: "Black Forest channel rod system with curtain carriers",
    title: "Channel rod detail",
    category: "System detail",
  },
  {
    src: "/images/gallery/forest/mcs-anthracite.webp",
    alt: "Anthracite multi channel curtain track creating a blackout overlap",
    title: "Blackout overlap track",
    category: "Hospitality",
  },
  {
    src: "/images/gallery/forest/fes-black.webp",
    alt: "Black Forest wave curtain track and evenly spaced curtain heading",
    title: "Black wave system",
    category: "Wave curtains",
  },
  {
    src: "/images/showcase/forest/recessed-wave.jpg",
    alt: "White wave curtains hanging below a discreet recessed track",
    title: "Recessed wave finish",
    category: "Wave curtains",
  },
  {
    src: "/images/gallery/forest/design-series-hotel.webp",
    alt: "Design curtain track profile shown in a hotel setting",
    title: "Hotel design track",
    category: "Hospitality",
  },
  {
    src: "/images/gallery/forest/shuttle-hotel.webp",
    alt: "Forest Shuttle motorised track in a hotel curtain setting",
    title: "Motorised hotel curtains",
    category: "Motorised",
  },
  {
    src: "/images/gallery/forest/voice-control-hotel.webp",
    alt: "Hotel curtains with voice and smart control options",
    title: "Smart curtain control",
    category: "Motorised",
  },
  {
    src: "/images/gallery/forest/mcs-hotel.webp",
    alt: "Multi channel curtain track detail for hotel blackout curtains",
    title: "Multi channel blackout",
    category: "Hospitality",
  },
  {
    src: "/images/gallery/forest/fes-hotel.webp",
    alt: "Forest wave curtain system in a refined hotel interior",
    title: "Hotel wave curtains",
    category: "Wave curtains",
  },
  {
    src: "/images/gallery/forest/cs-hotel.webp",
    alt: "Forest contract track used with heavy hotel curtains",
    title: "Contract track curtains",
    category: "Commercial",
  },
  {
    src: "/images/gallery/forest/acoustic-panel-track.webp",
    alt: "Curved ceiling track supporting acoustic curtain panels",
    title: "Acoustic panel track",
    category: "Commercial",
    format: "wide",
  },
  {
    src: "/images/showcase/forest/ks-profile.webp",
    alt: "White Forest KS curtain track profile and carriers",
    title: "Forest KS profile",
    category: "System detail",
  },
  {
    src: "/images/motorised/forest/fms-dual.png",
    alt: "Forest FMS Dual motorised curtain track system",
    title: "FMS Dual system",
    category: "Motorised",
  },
  {
    src: "/images/motorised/forest/shuttle-motor-range.png",
    alt: "Range of Forest Shuttle curtain motors",
    title: "Shuttle motor range",
    category: "Motorised",
  },
  {
    src: "/images/gallery/forest/easytouch-remote.webp",
    alt: "Forest EasyTouch remote control for motorised curtains",
    title: "EasyTouch control",
    category: "Motorised",
    format: "wide",
  },
  {
    src: "/images/motorised/forest/fms-track-colours.png",
    alt: "Forest motorised track profiles shown in white, grey and black",
    title: "Motorised track colours",
    category: "System detail",
  },
  {
    src: "/images/hero/trackfit-entry-poster.jpeg",
    alt: "Two discreet ceiling curtain tracks above full height curtains",
    title: "Ceiling mounted tracks",
    category: "Residential",
    format: "tall",
  },
];
